### ISSUE TITLE
Button native properties in SearchBar component

### ISSUE THREAD

**Issue by nabdali** [codegouvfr/react-dsfr#104]
I was wondering if it was necessary to add button native properties in the button inside search bar component.

**Comment by garronej** [comment]
Hi,  

I'm not sure I understand

**Comment by garronej** [comment]
@nabdali Oh yes that's true!  

I forgot about this because I my app at least the search result are provided in realtime without the user having to submit but sure I'd appreciate your PR!

**Comment by garronej** [comment]
Fixed
