### ISSUE TITLE
[BUG] Consent banner does not work as expected

### ISSUE THREAD

**Issue by desoindx** [codegouvfr/react-dsfr#114]
- The "Personnaliser" modal appears behind the banner
- It appears that only the last item of the consents is stored in the store

**Comment by garronej** [comment]
I'm on it

**Comment by garronej** [comment]
Sorry it isn't delivered yet. I'm still actively working on it.  https://github.com/codegouvfr/react-dsfr/pull/113  
When it eventually comes out it will be good.  
I will provide you with practical examples. At lease one with Google Analitics + Next.js App Router.

**Comment by garronej** [comment]
Still actively working on it, I'm making good progress, it should land soon enough.

**Comment by garronej** [comment]
Eventually, it landed:  

https://components.react-dsfr.fr/?path=/docs/components-consentmanagement--default 

Let me know if you need help to migrate to the new version, I can issue prs on your repo.  

I'm still working on the native integration with Eulerian...
