### ISSUE TITLE
[bug] style of error message in components that use a fieldset doesn't comply with dsfr 

### ISSUE THREAD

**Issue by isMattCoding** [codegouvfr/react-dsfr#121]
Error messages in components that use a fieldset (i.e. checkbox/radio/rich radio) are surrounded by `<div class="fr-messages-group">`, and the `p` child element has the `fr-message` and `fr-message--error` classes (see https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/case-a-cocher). 

Without these classes the border on the left of the component doesn't render correctly.

**Comment by enguerranws** [comment]
Hi @isMattCoding, I'm not sure I fully understood the issue, but [I submitted a PR](https://github.com/codegouvfr/react-dsfr/pull/149) to fix classes and tags mismatch on fieldsets (react-dsfr vs DSFR docs). 

Let me know if this should fix this issue.

**Comment by enguerranws** [comment]
Closing this, I guess the PR did the job.
