### ISSUE TITLE
Desync between storybook and code for RadioButtons

### ISSUE THREAD

**Issue by pom421** [codegouvfr/react-dsfr#130]
Hello, 

I used RadioButtons and the doc in Storybook doesn't reflect what is expected: 

In the [doc](https://react-dsfr-components.etalab.studio/?path=/docs/components-radiobuttons--default) :
<img width="756" alt="image" src="https://github.com/codegouvfr/react-dsfr/assets/3749428/62b975fc-9655-47c5-91ea-d7f1e014c952">

there is a prop label.

But in the v0.56.0, only legend seems accepted: 

<img width="637" alt="image" src="https://github.com/codegouvfr/react-dsfr/assets/3749428/34ae04de-c8fe-426c-a81c-b81aa2a8a06d">

**Comment by garronej** [comment]
Hello @pom421,  

Sory I only notice this issue now.  
Thanks for taking the time to report. It's fixed.
