### ISSUE TITLE
Remix Icon is breaking QuickAccessItems into Header

### ISSUE THREAD

**Issue by maximallain** [codegouvfr/react-dsfr#134]
# Context
I just migrated 2 libs in [my project](https://github.com/EIG6-Geocommuns/lidarviz-front) :
- react-dsfr : 0.54.0 => 0.57.4
- tss-react : 4.5.2 => 4.7.4

Then I discovered these regression

## Before
![image](https://github.com/codegouvfr/react-dsfr/assets/32595427/96478ed6-20ed-4c2a-9184-f32922f797ae)

## After
![image](https://github.com/codegouvfr/react-dsfr/assets/32595427/9586ea9f-6303-4106-a13b-de63af3fa369)

Here is the code
```ts
<Header
        brandTop={brandTop}
        serviceTitle={title}
        homeLinkProps={homeLinkProps}
        quickAccessItems={[
          {
            iconId: "fr-icon-account-circle-line",
            linkProps: {
              href: "#",
              className: classes.disabled,
            },
            text: "Me connecter",
          },
          {
            iconId: "ri-chat-3-line",
            linkProps: {
              href: feedbackLink || "#",
              target: "_self",
            },
            text: "Soumettre mes retours",
          },
          {
            iconId: "ri-mail-line",
            linkProps: {
              href: `mailto:${contactMail}`,
            },
            text: "Nous contacter",
          },
        ]}
        serviceTagline="Prototype - Version1 - 2023"
      />
```

# Solution path ?
I replaced Remix icons by dsfr icons, and it works backs.

![image](https://github.com/codegouvfr/react-dsfr/assets/32595427/d71c2eea-4c5d-4466-84b8-ca4ada8d86a1)

With this code
```ts
{
  iconId: "fr-icon-account-circle-line",
  linkProps: {
    href: feedbackLink || "#",
    target: "_self",
}
```

**Comment by garronej** [comment]
Thank you, I can reproduce.

**Comment by garronej** [comment]
By the way, this is something the visual regression testing should have cached 😞

**Comment by garronej** [comment]
Fixed in latest version, thanks for reporting!
