### ISSUE TITLE
Header and Footer should stay uncoupled

### ISSUE THREAD

**Issue by lsagetlethias** [codegouvfr/react-dsfr#141]
## Context
Given a next appDir app, as `Header` does not accept children, we sometimes have to make a "use-client" Header to handle authentification state.
For example with `next-auth`, we could use the "getServerSession()" function instead, and make everything "server-only", this this will opt-out everything to SSR and not static as "getServerSession()" use Next's `headers()` and `cookies()` functions internally.
The solution to avoid that is to use `useSession()` client hook, and leaf out the `Header` component into a client wrapper component.

The goal is to provide and DSFR compliant, and as much static as possible header avec `quickAccessItems` that include reactive items depending on a hook state.

Beside that, on the product marketing point of view, we need to have "onClick" and/or "href" from linkProps to have their own function (e.g. `onClick() { trackHeaderClick(); }`

## Pain
With `zz_internal/brandTopAndHomeLinkProps.ts` the coupling makes that we cannot have a client `Header` on one side, and a server/static `Footer` on the other.
I don't really see where resolving the pain of setting twos brand image or links was worth the drawback.
Also, it prevent us from having separated linkProps (e.g. adding different `utm_source` in the url), and DSFR doc doesn't precise if links and brands have to be the same.

On a side note, I know that this lib is not in v1 yet, but it could be really great if no API breaking changes like this one either be introduced, or by default, left undocumented on release notes.

## Proposed Solutions
1. Undo what was done with `zz_internal/brandTopAndHomeLinkProps.ts`
2. Make this coupling login less strict with a warning instead to allow both mechanics
3. Expose `setBrandTopAndHomeLinkProps()` to be used in an isomorphic setup
4. Allow Header's `quickAccessItems` to accept "ReactNode" like `navigation` props

**Comment by garronej** [comment]
Apologies for the less than ideal experience. I'm currently in the process of refining the App Router and learning about various usage scenarios, which means that there may be some hiccups along the way. I acknowledge that there are instances where the Header would be on the client side, and not the Footer - this was something that I did not initially anticipate.

As for your concerns about introducing breaking changes without sufficient documentation - I understand and appreciate your feedback. Although the library hasn't reached v1 yet, I want to retain the flexibility to iterate quickly. Once we reach v1 (which should be soon), I intend to version the documentation and will provide a migration guide for each breaking change. 

I make it a point to keep the demo setup and the documentation as up-to-date as possible. However, in this instance, I admit I overlooked some updates. I appreciate you bringing [this issue](https://github.com/codegouvfr/react-dsfr/pull/140) to my attention.

During this pre-v1 stage, I'd be more than willing to issue pull requests to your repository if I introduce any other breaking changes.

The coupling of the Header and Footer, while a bit unconventional, is intended to enhance the developer experience. This, of course, is under the assumption that everything functions as intended.

You brought up a valid point about the Header not accepting children. This is an issue I've been addressing in the new GDPR branch, where I'm enabling the use of custom React nodes as items in the Header and Footer. This is precisely to allow the use of client components without needing to wrap the Header/Footer within a `"use client";` directive.

Considering all these points, I'll be pushing a fixed version that addresses them. Please bear with me during this process and thank you for your patience and valuable feedback.

**Comment by garronej** [comment]
In summary:

- You now have the option to explicitly pass `brandTop` and `homeLinkProp` to the `<Footer />` as was previously possible. If these are not supplied, an attempt will be made to retrieve them from the `<Header />`.
- It is now possible to create any Header `quickAccessItem` on the client side without the need to wrap the entire Header in `"use client";`. For more details, please refer to [the note in Storybook](https://react-dsfr-components.etalab.studio/?path=/docs/components-header--simple-header).
- The same applies for Footer's `bottomItems`.

> Additionally, from a product marketing perspective, it would be beneficial if linkProps like "onClick" and/or "href" could have their unique functions (e.g., onClick() { trackHeaderClick(); }). 

While I might not fully grasp your statement, it's worth noting that a Header quick access item can indeed [be a button](https://github.com/codegouvfr/react-dsfr/blob/6324ebdc1085a697ba1ee06c9eceacf768ca8895/src/Header.tsx#L86-L92), and therefore, it can possess an `onClick` function. 

Here is an example:

https://github.com/codegouvfr/react-dsfr/blob/0b6f5b8af9de1bbc79d91cc3dd25e12d8e807fbe/test/integration/next-appdir/ui/ClientHeaderQuickAccessItem.tsx#L1-L25  

I hope these improvements address all your concerns. Thank you for bringing these issues to our attention.

**Comment by lsagetlethias** [comment]
Great! Thank you for the changes 🎉
Feels nice to have a flexible Header.

> Beside that, on the product marketing point of view, we need to have "onClick" and/or "href" from linkProps to have their own function (e.g. onClick() { trackHeaderClick(); }
I was talking about the `homeLinkProps` which may need to have a different behaviour depending if the header link or the footer link was clicked.

**Comment by garronej** [comment]
Thanks for the feedback! 

> I was talking about the homeLinkProps which may need to have a different behaviour depending if the header link or the footer link was clicked.  

Oh I see!  

Sorry for the borken link in my reply, [here](https://react-dsfr-components.etalab.studio/?path=/docs/components-header--simple-header#header-with-quick-access-items) you have links to an example usage of a client side header quick access item with the header used a server component.
