### ISSUE TITLE
problème d'accessibilité sur les modals de la nouvelle version 0.6x.x

### ISSUE THREAD

**Issue by youssefElMkhantar** [codegouvfr/react-dsfr#145]
Bonjour,

j'ai rencontré un problème d'accessibilité au niveau de la nouvelle version du modal. en fait meme si je définis un boutton et un onClick pour ouvrir manuellemnt le modal. la fonction creatModal() semble créer un boutton invisible sans lui donner de text. ce qui est confirmé par les essais que j'ai fait. voici quelques photos du problème.

Merci

![erreur_accessibilite](https://github.com/codegouvfr/react-dsfr/assets/55538110/9f96580e-9cf2-45a4-bf87-5865d8ae4133)

![button_accessibilite](https://github.com/codegouvfr/react-dsfr/assets/55538110/4a52fa44-8d6a-48e0-8191-91fc07da2531)

![handle_accessibilite](https://github.com/codegouvfr/react-dsfr/assets/55538110/e241b940-77a5-4ad6-a613-876fa93fbed1)

**Comment by garronej** [comment]
Bonjour @youssefElMkhantar,  
Merci pour avoir fait remontrer, je vois le problème. Je vais tacher de corriger.

**Comment by garronej** [comment]
Hello @youssefElMkhantar,  

In response to the recent challenge concerning the invisible button in DSFR, it appears there is no straightforward method to remove it without compromising the server-ready status of the Modal component.

To counteract this limitation, I have implemented the following attributes on the respective buttons: 

```html
    tab-index="-1",
    aria-hidden="true"
```
These modifications are intended to enhance our accessibility compliance. However, should your accessibility tools continue to flag any issues, kindly let me know so we can address them promptly.

If necessary, I am prepared to collaborate with the @gouvfr/dsfr team to explore further solutions, ensuring we meet all accessibility requirements.

Thank you for your understanding, and I look forward to your feedback.

Best regards,

**Comment by youssefElMkhantar** [comment]
Hello @garronej 
thanks, problem solved after updating to the latest version.

**Comment by garronej** [comment]
cool, thaks for the feedback!
