### ISSUE TITLE
Description in Alert component

### ISSUE THREAD

**Issue by enguerranws** [codegouvfr/react-dsfr#146]
I'm using <Alert /> component to display feedback on action like this:

![Capture d’écran 2023-07-20 à 10 44 49](https://github.com/codegouvfr/react-dsfr/assets/2190121/d1edfcee-5260-45e8-ba62-61d7a8502438)

As you can see, I'm using a unordered list to display errors (in that case). I have several cases like this where I want to provide feedback via an Alert component as separate items. That's not how the DSFR Alert component has been designed, as its description should simply be included in `<p>` tag (as per documentation : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/alerte/).

The issue is that including `<ul>` in a `<p>` is not valid HTML (and produces warning in the console...).

Should we stick to the DSFR markup? Switch to a generic `<div>` instead of a `<p>` ? Maybe the DSFR team is ok with using an other tag than the `<p>`?

**Comment by garronej** [comment]
Hello @enguerranws,  

You are right. I don't know what's the best approach to tackle this though

**Comment by enguerranws** [comment]
I did ask the DSFR team about this (https://mattermost.incubateur.net/betagouv/pl/pjiwmqbc8bb7znk86aqh49h8xc). It seems that the example in the doc is just a markup example, that can be adjusted (e.g. using an <ul> to show errors as list). I'll push something to adjust our component to handle it in a few days.

**Comment by enguerranws** [comment]
PR to review: https://github.com/codegouvfr/react-dsfr/pull/148
