### ISSUE TITLE
Add title for footer links that open in a new tab

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#153]
This issue has been raised by an accessibility audit on an app using react-dsfr.

The 4 hardcoded links in the footer to "legifrance.gouv.fr", "gouvernement.fr", "service-public.fr" and "data.gouv.fr" open in a new tab (`taget="_blank"`).

They should bear titles like : "legifrance.gouv.fr - ouvre une nouvelle fenêtre"
This is not the case on our app and on the [Footer component documentation](https://components.react-dsfr.codegouv.studio/?path=/docs/components-footer--default) 

Should the Footer component be modified or should it be added by another script ?

**Comment by garronej** [comment]
Hi @slafayIGN,  
Thanks for rising the issue
I guess the footer component should be modified in this instance.  I'll do it this week end.

**Comment by pprev94** [comment]
Hi, I'm working on it

**Comment by garronej** [comment]
Sorry I forgot to address this.  

Thank you for working on this. Your change LGTM, don't forget to open a PR!

**Comment by slafayIGN** [comment]
Merged and available for versions >=[ v0.75.0](https://github.com/codegouvfr/react-dsfr/releases/tag/v0.75.0) 🚀

🙏
