### ISSUE TITLE
nativeInputProps aren't passed to the underlying input in Upload component

### ISSUE THREAD

**Issue by ocruze** [codegouvfr/react-dsfr#155]
Hi, I tried to use the Upload component and the `onChange`was never getting called. So I looked into the code and it seems that the `nativeInputProps` aren't passed to the underlying input. I tried a dirty fix and passed the `nativeInputProps` to the inner input and it worked. If you'd like I can provide a PR.

**Comment by garronej** [comment]
Thanks a lot for the report.  
Yes please we'd appreciate a PR!
