### ISSUE TITLE
No type on textarea

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#159]
The Input component shouldn't add the `type` attribute when the Input is a `<textarea>`.

The `<textarea>` HTML element has no type.

The current behaviour outputs `type="text"`, which makes the HTML document invalid and can lead to accessibility issues.

**Comment by garronej** [comment]
Hello @slafayIGN,  
Thank you for letting us know!   
Would you be willing to submit a PR?
