### ISSUE TITLE
Choose Hx level for Card title

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#160]
The Card component title is always a h3 : https://github.com/codegouvfr/react-dsfr/blob/39140e5146f57fef88e8cfea8f86f9932fe90472/src/Card.tsx#L149-L160

In order not to mess with the actual document hierarchy, we should be able to choose the title level we want.

This has already been done in the Accordion component with a `titleAs` property. A similar behaviour would be appropriate.

(I can work on the PR later)

**Comment by garronej** [comment]
Agreed, thanks for pointing it out.  
Yes a PR would be appreciated!

**Comment by slafayIGN** [comment]
Merged and available for versions >=[ v0.74.0](https://github.com/codegouvfr/react-dsfr/releases/tag/v0.74.0) 🚀 

Thank you guys
