### ISSUE TITLE
pb d'utilisation du composant Pagination

### ISSUE THREAD

**Issue by Datayama38** [codegouvfr/react-dsfr#170]
Bonjour,
J'essaye d'intégrer le composant de pagination dans une page mais la doc manque d'info par rapport à l'utilisation de la prop getPageLinkProps
J'ai essayé de prendre exemple sur les stories d'exemple : 
`getPageLinkProps= {pageNumber => { return {href: `/page/${pageNumber}`}}}`
Je n'ai pas d'erreur ts dans VSCode mais à la compilation nextjs me renvoi une erreur :
`Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead.
    at Array.forEach (<anonymous>)
null`
Une idée ?
Merci d'avance

**Comment by Datayama38** [comment]
Je viens de remarquer que si la prop defaultPage à une valeur > 1 alors le composant s'affiche

**Comment by enguerranws** [comment]
Je ne sais pas si le souci est résolu, mais voici un exemple d'utilisation dans une SPA : https://github.com/gip-inclusion/immersion-facile/blob/main/front/src/app/components/search/SearchListResults.tsx#L123

> Error: Failed prop type: The prop href expects a string or object in, but got undefined instead. at Array.forEach (<anonymous>) null

Je pense qu'il faudrait que j'en vois plus pour comprendre pourquoi dans ce cas, `href` est `undefined`.

**Comment by enguerranws** [comment]
@Datayama38 Ce souci est toujours d'actualité ?

**Comment by ClementNumericite** [comment]
oui le problème persiste, de ce que je comprends :
- Dans le <Link /> de NextJS href est required ([cf doc](https://nextjs.org/docs/pages/api-reference/components/link#href-required))
- Pour les liens first, previous, next & last dans le composant <Pagination /> on récupère `getPageLinkProps` conditionnellement pour pouvoir disable ces liens lorsqu'ils ne sont pas pertinents (en page 1 ou à la dernière page) ([cf code](https://github.com/codegouvfr/react-dsfr/blob/30b16b365b1ae78da89362fd5c639446ddb42de3/src/Pagination.tsx#L104))
- Ce qui fait que le composant <Link /> n'a plus de href = Error
- Info complémentaire, le CSS du dsfr cible bien les liens sans href pour appliquer les styles "disabled"

![Screenshot from 2023-09-28 10-22-19](https://github.com/codegouvfr/react-dsfr/assets/80679266/0e44b686-0898-422b-b2a5-d09201ca9376)
![Screenshot from 2023-09-28 10-22-08](https://github.com/codegouvfr/react-dsfr/assets/80679266/ca765b9a-abd3-4dd3-9e18-fbafbb6e4150)

Du coup je pense que la solution est de remplacer le <Link /> par un <a> sans href si les conditions sont vraies...?

**Comment by Datayama38** [comment]
oui, le problème persiste.
Je m'en suis sorti en créant moi-même un composant de pagination en m'inspirant du vôtre:
https://github.com/betagouv/preuve-covoiturage/blob/main/public/src/components/common/Pagination.tsx

**Comment by ClementNumericite** [comment]
merci @Datayama38 , 
ok tu remplaces l'élément `<Link/>` par des `<p>` quand le defaultPage a les valeurs concernées.

je vais proposer une PR, mais je pensais remplacer par des `<a>` sans href pour respecter strictement ce que fait le dsfr atm. ([cf pagination dsfr](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/pagination/))
@garronej un avis avant que je me lance ?

(cc @BrianRid)

**Comment by martinratinaud** [comment]
> merci @Datayama38 , ok tu remplaces l'élément `<Link/>` par des `<p>` quand le defaultPage a les valeurs concernées.
> 
> je vais proposer une PR, mais je pensais remplacer par des `<a>` sans href pour respecter strictement ce que fait le dsfr atm. ([cf pagination dsfr](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/pagination/)) @garronej un avis avant que je me lance ?
> 
> (cc @BrianRid)

J'ai le meme problème et il faudrait aussi qu'on puisse ne pas avoir un Link mais un Button

J'essaye de l'utiliser avec le Datagrid de MUI et on récupère un onClick. Si c'est un Link, je vais etre obligé de mettre un href="#" qui sera pas magique ou alors de faire un e.preventDefault()

**Comment by garronej** [comment]
Thanks for working on this, it has been fixed by #273
