### ISSUE TITLE
Import dsfr/dsfr.module.min

### ISSUE THREAD

**Issue by enguerranws** [codegouvfr/react-dsfr#174]
Hi,

Working on a component, I've noticed that `react-dsfr` is importing `dsfr/dsfr.module.min.js` (the JS part of `@gouvfr/dsfr`). 

![Capture d’écran 2023-08-28 à 15 23 42](https://github.com/codegouvfr/react-dsfr/assets/2190121/b5b6506d-3794-4e75-a958-11d9cf41933c)

(in the non-bundled version, it seems to be imported by [src/start.ts line 47-48](https://github.com/codegouvfr/react-dsfr/blob/main/src/start.ts#L47)):

```
    // @ts-expect-error
    await import("./dsfr/dsfr.module.min");
```

From what I understand, we're expecting that this file can't be imported.
But it seems that it is imported at runtime because at runtime, `start.js`imports `./dsfr/dsfr.module.min` which is in `dist` folder.

Is this behavior (importing dsfr.module.min from `react-dsfr`) expected?

**Comment by garronej** [comment]
Hello @enguerranws,

Yes, the behavior you observed is expected, and here's why:

0) There's no urgent need for the JS code of the core DSFR to load early on.

1) To avoid white flashes in dark mode, certain operations must be executed both before and after the script is evaluated. Dynamically importing the script simplifies this process, eliminating the need to check its loading status elsewhere.

2) For user-specific configurations like Eulerian analytics, it's easier to manage these if the script is dynamically imported. This approach minimizes the risk of the script initializing incorrectly.

3) We aim to make the setup process as straightforward as possible. Whenever we can abstract away an import, we opt to do so for the sake of simplicity.

I hope this clarifies any questions you may have.

Best regards,

**Comment by enguerranws** [comment]
Ok, I get it. 

I still have one question though: the script file is importing behavior related to components. For example, the tooltip relies on tooltip.module.js (bundled in dsfr.module.min) to handle tooltip's appearing / positionning logic. When implementing this component in `react-dsfr`, I thought we would get rid of pure JS logic and reimplement it fully in React?

**Comment by garronej** [comment]
Ah, I see where you're coming from with your question. react-dsfr serves as an integration toolkit for @gouvfr/dsfr, rather than a reimplementation of the DSFR framework. Maintaining this integration-as-is is crucial for securing continued approval from the SIG.

While adhering to this paradigm introduces notable challenges—such as implementing complex logic to simply indicate whether a modal is open or closed ([See code](https://github.com/codegouvfr/react-dsfr/blob/main/src/Modal/useIsModalOpen.ts))—it also offers significant advantages. For instance, this approach allows us to delegate the component behavior implementation and ensures compatibility with React Server Components. This is particularly compelling in 2023, given that many UI libraries are still overly reliant on `"use client";`, whereas most of our components are RSC ready.

**Comment by enguerranws** [comment]
@garronej So in the case of the Tooltip component, what should we do? Right now it's kinda hard to reimplement original JS tooltip logic in React because DSFR JS integration is overriding most of the things we could do (by adding event listeners, etc).

**Comment by garronej** [comment]
I think we shouldn't attemt to do anything more than what the `@gouvfr/dsfr` is doing.  
We shounld NOT reimplement the logic in React.  We should never re-implement any logic already handled by the core library.  

The way I see it should look something like:  

```tsx
import { useTooltip } from "@codegouvfr/react-dsfr/Tooltip";

...

const tooltip = useTooltip();


return (
<>
<a class="fr-link" aria-describedby={tooltip.id} href="#">
    Exemple
</a>
<tooltip.Component>
Lorem [...] elit ut.
</tooltip.Component>

);
```

`Tooltip.tsx`
```tsx
import { useId, type ReactNode } from "react";

export function useTooltip() {

    const id = useId();

    return {
        id,
        "Component": (props: Omit<Props, "id">) => <TooltipComponent {...props} id={id} />
    }


}

type Props = {
    className?: string;
    children: ReactNode;
    id: string;
};

function TooltipComponent(props: Props) {
    const { id, className, children } = props;
    return (
        <span className={cx(fr.cx("fr-tooltip", "fr-placement"), className)} id={id} role="tooltip" aria-hidden="true">
            {children}
        </span>
    );

}
```
