### ISSUE TITLE
Override Upload labels

### ISSUE THREAD

**Issue by myusername44** [codegouvfr/react-dsfr#192]
Bonjour, peut-on override les labels du composant Upload ?

Le composant n'exporte pas les fonctions useTranslation et addUploadTranslations.

Sur le composant Header  les fonctions sont bien exportés donc on a bien la main pour override les labels.

https://github.com/codegouvfr/react-dsfr/blob/563faa1781c6337c31bc794f48d5a0b592333d7d/src/Upload.tsx#L117

Merci

**Comment by garronej** [comment]
Thanks for the heads up!  
The issue has been adressed, a new version is being relesed.  

Best regards
