### ISSUE TITLE
icons problem

### ISSUE THREAD

**Issue by youssefElMkhantar** [codegouvfr/react-dsfr#193]
hi,

i recently encountred a problem in accordion and alert components. the icons doesn't show but instead a square is present.
i use react with vite.js

thank you

**Comment by ddecrulle** [comment]
Hello,

Have you carefully followed the installation procedure described in the documentation ? An example project is available [here](https://github.com/garronej/react-dsfr-vite-demo)

**Comment by youssefElMkhantar** [comment]
i did the exact same thing. 
a month ago it worked just fine but lately after some updates.icons don't show anymore !!

**Comment by ddecrulle** [comment]
I need more context to help you

**Comment by youssefElMkhantar** [comment]
here is the actual results following the same for vite in the docs 

<img width="1416" alt="Screenshot 2023-09-20 at 17 48 13" src="https://github.com/codegouvfr/react-dsfr/assets/55538110/fd4ecc90-50f6-4f63-b83b-63932c73babd">



<img width="1438" alt="Screenshot 2023-09-20 at 17 49 38" src="https://github.com/codegouvfr/react-dsfr/assets/55538110/cfee319e-bf76-4b57-a40f-630992d8bb53">



<img width="1440" alt="Screenshot 2023-09-20 at 17 52 27" src="https://github.com/codegouvfr/react-dsfr/assets/55538110/ffe3aa4f-0937-424d-b438-3425041277a9">



<img width="1373" alt="Screenshot 2023-09-20 at 17 50 38" src="https://github.com/codegouvfr/react-dsfr/assets/55538110/e69bf266-d3d9-4a22-8cdf-30d6c088d989">

**Comment by youssefElMkhantar** [comment]
```
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "postinstall": "copy-dsfr-to-public",
    "predev": "only-include-used-icons",
    "prebuild": "only-include-used-icons"
  },
  "dependencies": {
    "@codegouvfr/react-dsfr": "^0.74.2",
    "@dataesr/react-dsfr": "^3.6.0",
    "@emotion/style": "^0.8.0",
    "@emotion/styled": "^11.11.0",
    "@jitsi/react-sdk": "^1.3.0",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.12.3",
    "@reduxjs/toolkit": "^1.9.5",
    "@types/react-datepicker": "^4.11.2",
    "@types/react-mic": "^12.4.3",
    "axios": "^1.4.0",
    "dotenv": "^16.0.3",
    "jwt-decode": "^3.1.2",
    "react": "^18.2.0",
    "react-datepicker": "^4.14.0",
    "react-datetime-picker": "^5.2.0",
    "react-dom": "^18.2.0",
    "react-icalendar-link": "^3.0.2",
    "react-markdown": "^8.0.7",
    "react-mic": "^12.4.6",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.11.1",
    "react-slideshow-image": "^4.2.1",
    "react-webcam": "^7.0.1",
    "rehype-raw": "^6.1.1",
    "remark-slug": "^7.0.1"
  },
  "devDependencies": {
    "@types/node": "^20.1.5",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "@vitejs/plugin-react": "^4.0.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "prettier": "^2.8.8",
    "typescript": "^5.0.2",
    "vite": "^4.3.2"
  }
}
```

**Comment by garronej** [comment]
@youssefElMkhantar Sorry about that.  
Can you share your code or a reproducable repo?  
I'll fix swiftly.

**Comment by ddecrulle** [comment]
Unfortunately I can't reproduce your issue, as you can see [here](https://react-dsfr-vite-demo.vercel.app/) and [check code](https://github.com/garronej/react-dsfr-vite-demo/blob/main/src/Home.tsx#L24~L31), icons are well displayed.

**Comment by youssefElMkhantar** [comment]
thanks for the responses. here is the demo project. you can see yourself
https://github.com/DISIC/wce-portail

**Comment by ddecrulle** [comment]
Ok I reproduced and fixed, this occurs only when `<Badge>` in Header.tsx is used. I had to add `@emotion/react` to your project otherwise it won't build. Also `npm install` doesn't work either, I installed the dependencies with yarn. 

<img width="673" alt="Capture d’écran 2023-09-20 à 22 31 36" src="https://github.com/codegouvfr/react-dsfr/assets/81740200/084aa4d3-cf4c-4acd-95ce-fb749dd6cb2a">

**Comment by youssefElMkhantar** [comment]
thanks. finnaly it worked for me. the problem was the use of dataesr/react-dsfr component in the same project with the new design system.
