### ISSUE TITLE
Menu in MainNavigation component not closing

### ISSUE THREAD

**Issue by Datayama38** [codegouvfr/react-dsfr#198]
Bonjour,
J'ai créé un composant Nextjs qui utilise le composant MainNavigation et je rencontre un pb dans le comportement des menus:
En cliquant sur un item du menu, le lien redirige correctement sur la bonne page mais le menu ne se referme pas.
J'ai déjà eu un soucis similaire sur un autre projet en utilisant le composant <Link> que j'avais remplacé par un <a> pour régler le pb.

Y a t'il une variable à ajouter à linkProps ?

Mon code: https://github.com/betagouv/preuve-covoiturage/blob/main/public/src/components/layout/Navigation.tsx
Le site pour voir le comportement en live: https://demo.covoiturage.beta.gouv.fr

**Comment by garronej** [comment]
Bonjour @Datayama38,  

Je crois malheureusement que c'est le comportement du composant et non un bug de react-dsfr.  
Je vais demander confirmation a l'équipe DSFR sur le slack.  

Je conviens que c'est problématique, il faut trouver une solution.

**Comment by garronej** [comment]
Il y a eu une régression dans @gouvfr/dsfr, ça va être corrigé très vite. Dès qu'il publient le correctif je met a jour la version pinné dans react-dsfr.

**Comment by SylvainLtt** [comment]
Bonjour @garronej,
Est-ce que fix a été fait coté DSFR ?
Merci

**Comment by Datayama38** [comment]
Bonjour,
A priori le fix n'a pas encore été fait car je constate toujours le pb après avoir fais les dernières maj

**Comment by garronej** [comment]
Bonjour @SylvainLtt et @Datayama38,  
Je viens à l'instant d'update la version @gouvfr/dsfr utilisé par @codegouvfr/react-dsfr a la dernière version.  
Si le bug a été corrigé upstream ça sera aussi le cas dans react-dsfr.  

Pourriez vous me remonter si c'est le cas que je ferme l'issue.

**Comment by Datayama38** [comment]
Bonjour,
De mon côté, rien n'a changé avec la dernière version. Le menu ne se ferme toujours pas.
Pour info, J'ai utilisé la méthode "Navigation As Custom Node" décrite dans la doc pour l'implémentation dans une app Next 13 AppDir. Le code est dispo ici : https://github.com/betagouv/preuve-covoiturage/blob/main/public/src/components/layout/Navigation.tsx
Je me demande si le pb ne vient pas de l'utilisation du component Link au lieu de simples balises <a> pour les items du menu.

**Comment by garronej** [comment]
Oui je constate en effet que je problème n'es toujours pas résolu.  
C'est assez serieux je vais recontacter l'équipe DSFR.  
@Datayama38 quand a l'utilisation du routing client, en effet si nous rechargions entèrement l'app lors de la navigation vers une autre page le menu se fermerais mais ce n'es pas ce que l'on veut ici.  

https://github.com/codegouvfr/react-dsfr/assets/6702424/b080dc97-5f92-4b30-bbe3-377bac1203f8

**Comment by garronej** [comment]
<img width="660" alt="image" src="https://github.com/codegouvfr/react-dsfr/assets/6702424/e7a6ea97-61cd-414b-9fab-2fdcb7f0432e">

**Comment by Datayama38** [comment]
issue fixed in v1.7.3

**Comment by garronej** [comment]
Great thanks for the update!
