### ISSUE TITLE
Badge element can also be a span

### ISSUE THREAD

**Issue by sbourdon13** [codegouvfr/react-dsfr#200]
Currently, the Badge element is a `<p>`, but it could also be a `<span>` when the Badge is used inside a \<p>.
For example, in the header title, I need a span to avoid the error `<p> cannot appear as a descendant of <p>`.

See example "Header avec bandeau BETA" at https://main--ds-gouv.netlify.app/example/component/header/

**Comment by garronej** [comment]
Thank you!
