### ISSUE TITLE
Change french licence statement

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#207]
Since [DSFR v1.9.1](https://github.com/GouvernementFR/dsfr/releases/tag/v1.9.1), the licence text in the footer has [changed](https://github.com/GouvernementFR/dsfr/pull/568/files).

A PR will follow with the change in the Footer component.

**Comment by slafayIGN** [comment]
PR #208

**Comment by garronej** [comment]
great

**Comment by garronej** [comment]
Thank you
