### ISSUE TITLE
MUI DataGrid TrustedHTML problem

### ISSUE THREAD

**Issue by garronej** [codegouvfr/react-dsfr#210]
Hello @lsagetlethias,  

I was hoping maybe you could help me understand this. 
The Mui DataGrid no longer work in the Next App router test setup:  

![image](https://github.com/codegouvfr/react-dsfr/assets/6702424/b98b6c9f-2bdf-41ad-8e99-382a5dcedc09)

Any idea how to address this?  

Thanks in advance for your help!

**Comment by lsagetlethias** [comment]
This is linked to trusted types policies and this error should only appears on Chrome (for now).
Either MUI is now setting HTML to innerHTML without using trusted types (which is unsafe), or a error is thrown by something else, and the "catcher" (maybe ReactDOM) is trying to display the error with innerHTML.

Disabling trusted types in dev should, I think, resolve the issue.

**Comment by garronej** [comment]
yes let's go, after eading your answer I figured out that maybe upgrading MUI would solve the issue. Sure enough it did.  
Thanks for the help!
