### ISSUE TITLE
Select id  native props 

### ISSUE THREAD

**Issue by Thorekt** [codegouvfr/react-dsfr#212]
Hi,

In Input.tsx, you can give an 'id 'to the input by passing id in "nativeInputProps".

In Select.tsx you can't give an 'id' to the select even by putting it in "nativeSelectProps".

I suggest to look what is done in Input.tsx and do the same in Select.tsx 

I can give more informations if you need.

**Comment by garronej** [comment]
Hey @Thorekt,  

Thanks for reporting, it's fixed.  
A new version is being deployed.

**Comment by Thorekt** [comment]
Hi, 
The bug seems still here, i saw  your modification but it's override by the "selectId" comming after 
`

        const id = useAnalyticsId({
            "defaultIdPrefix": "fr-select-group",
            "explicitlyProvidedId": id_props ?? nativeSelectProps.id
        });

        const selectId = `select-${useId()}`;
` 
the select element use "selectId" :

`
<select
    {...nativeSelectProps}
    className={cx(fr.cx("fr-select"), nativeSelectProps.className)}
    id={selectId}
    aria-describedby={stateDescriptionId}
    disabled={disabled}
>
    {children}
</select>
`

I think the id in "nativeSelectProps" is overide by the id using "selectId" 

Thanx for your reactivity
