### ISSUE TITLE
Problème de sémantique HTML dans le composant Header

### ISSUE THREAD

**Issue by humchaop** [codegouvfr/react-dsfr#216]
Il y a une erreur de sémantique dans le composant Header.
Le texte du logo "Intitulé officiel" est dans une balise `<p>` inclus dans une balise `<a>`.
Les balises `<p>` n'étant pas autorisées dans les balises `<a>`, nous avons une anomalie d'accessibilité.

Il faudrait supprimer la balise `<p>` ou la remplacer par un `<span>`.

Exemple de code : 
Composant header simple
![Composant Header simple](https://github.com/codegouvfr/react-dsfr/assets/156206391/a2838013-332a-4c6c-8e8a-274a74e44ef8)

Composant Header simple avec nom du service
![Composant Header simple avec nom du service](https://github.com/codegouvfr/react-dsfr/assets/156206391/43fb98f0-be20-4886-a085-bf801a1a005c)

**Comment by garronej** [comment]
Pourrais tu regarder si c'est le cas dans le template officiel?  
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete  

Si c'est le cas, il faudrais traitée cette issue upstream avant

**Comment by humchaop** [comment]
C'est bien le cas. Quelle est la marche à suivre dans ce cas ?

**Comment by garronej** [comment]
Rejoindre le slack du DSFR et reporter le problème sur le canal #aide_dev.  
Je vais le faire.

**Comment by enguerranws** [comment]
Ah, je n'avais pas vu la discussion et ai répondu sur l'issue du footer : https://github.com/codegouvfr/react-dsfr/issues/217#issuecomment-1892281387

**Comment by enguerranws** [comment]
Pour suivre plus simplement la discussion, je copie mon retour ici : 

> Inclure des balises block dans un élément <a> était une erreur de validation en HTML / XHTML 4 et moins, ce n'est plus le cas en HTML5.
> Ça ne pose (à ma connaissance), pas de souci d'accessibilité également : l'arbre d'accessibilité me semble clean (cf. screenshot), l'élément est bien accessible au clavier et la lecteur de texte fonctionne bien également.
> ![Capture d’écran 2024-01-15 à 15 27 35](https://github.com/codegouvfr/react-dsfr/assets/2190121/6140b577-b664-4638-9356-bd67fb209a9c)
> @humchaop Je reste à dispo si tu constates un impact négatif, pour éventuellement faire remonter ça à l'équipe du DSFR (ici, nous ne faisons que suivre l'implem HTML / CSS qu'ils mettent en place).

**Comment by garronej** [comment]
@humchaop 

<img width="705" alt="image" src="https://github.com/codegouvfr/react-dsfr/assets/6702424/73fbfbb0-40d6-443e-a542-66570ffc7749">

**Comment by enguerranws** [comment]
@humchaop aussi, n'hésite pas à partager l'url de ton projet (si tu peux).

**Comment by humchaop** [comment]
@enguerranws je ne peux pas ce sont des projets internes du MEAE

**Comment by enguerranws** [comment]
@humchaop des nouvelles au sujet de cette demande ?

**Comment by enguerranws** [comment]
@humchaop s'il n'y a pas de nouvelles, je propose de clore le ticket.
