### ISSUE TITLE
Problème de sémantique HTML dans le composant Footer

### ISSUE THREAD

**Issue by humchaop** [codegouvfr/react-dsfr#217]
Il y a une erreur de sémantique dans le composant Footer.
Le texte du logo "Intitulé officiel" est dans une balise `<p>` inclus dans une balise `<a>`.
Les balises `<p>` n'étant pas autorisées dans les balises `<a>`, nous avons une anomalie d'accessibilité.

Il faudrait supprimer la balise `<p>` ou la remplacer par un `<span>`.

Exemple de code :
Composant Footer default
![Composant Footer default](https://github.com/codegouvfr/react-dsfr/assets/156206391/3a7cb964-367b-4bb7-b553-9e7bb9999a35)

**Comment by enguerranws** [comment]
Inclure des balises block dans un élément `<a>` était une erreur de validation en HTML / XHTML 4 et moins, c'est n'est plus le cas en HTML5.
Ça ne pose (à ma connaissance), pas de souci d'accessibilité également : l'arbre d'accessibilité me semble clean (cf. screenshot), l'élément est bien accessible au clavier et la lecteur de texte fonctionne bien également. 

![Capture d’écran 2024-01-15 à 15 27 35](https://github.com/codegouvfr/react-dsfr/assets/2190121/216fef71-8de3-4a54-9002-a48161e3371b)

@humchaop Je reste à dispo si tu constates un impact négatif, pour éventuellement faire remonter ça à l'équipe du DSFR (ici, nous ne faisons que suivre l'implem HTML / CSS qu'ils mettent en place).

**Comment by enguerranws** [comment]
@humchaop s'il n'y a pas de nouvelles, je propose de clore le ticket.
