### ISSUE TITLE
Working on Follow component

### ISSUE THREAD

**Issue by lsagetlethias** [codegouvfr/react-dsfr#219]
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/lettre-d-information-et-reseaux-sociaux/

**Comment by garronej** [comment]
Top merci beaucoup @lsagetlethias, je regarde tout a l'heure

**Comment by lsagetlethias** [comment]
T'embêtes pas, c'est toujours en WIP pour le moment. Je te ping le moment venu. ;)

**Comment by garronej** [comment]
ça marche!

**Comment by lsagetlethias** [comment]
@garronej RFR
