### ISSUE TITLE
Update consentManagement stories

### ISSUE THREAD

**Issue by enguerranws** [codegouvfr/react-dsfr#230]
I'm currently installing the consentManagement on [IF](https://immersion-facile.beta.gouv.fr/). 

First, **many thanks to those who worked on this**, it took 5 minutes to install and make it work with our cookies (and well, writing the labels took the most of the time).

[The stories](https://components.react-dsfr.codegouv.studio/?path=/docs/components-consentmanagement--default) seem out of date, the Placeholder component doesn't seem to be defined in the project. 

I can clean it up in the next few days.

**Comment by garronej** [comment]
@enguerranws   

Thank you dude! Took me a bunch of time and effort to come up with this. @lsagetlethias worked a lot as well.  
You care correct regarding the `<Placeholder />` it's not that it's out of date, it's just that I got a bit discouraged and I didn't go the extra miles of implementing it.  
You can either remove it from the story or even better, add the component for it!

**Comment by enguerranws** [comment]
@garronej Sure, I didn't understand what was this Placeholder component, but I just checked [the docs](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/gestionnaire-de-consentement) and it's clear now. 

I'll take a look at this as soon as possible.

**Comment by enguerranws** [comment]
Closed by https://github.com/codegouvfr/react-dsfr/pull/232
