### ISSUE TITLE
Search Bar :  Demande d'ajout de fonctionnalités

### ISSUE THREAD

**Issue by Thorekt** [codegouvfr/react-dsfr#240]
Bonjour,
Dans le cadre d'une recherche d'élément provenant d'une api, j'aimerais voir deux fonctionnements être ajoutés à la search bar :

1. Possibilité de ne pas vider le champ de recherche lorsque l'on clique sur le bouton de recherche.
2. Possibilité de faire une recherche avec le champ vide. En effet, si j'effectue une recherche et que je veux revoir la liste au complet, je suis obligé d'actualiser la page, car la search bar ne trigger pas mon onButtonClick() si le champ est vide

Merci d'avance pour votre intervention

**Comment by garronej** [comment]
Hello @Thorekt,  

It's done.  

You can now use:  

```tsx
<SearchBar  
   allowEmptySearch
   clearInputOnSearch={false}
/>
``` 

It's also available on the Header.  

See doc:  

https://components.react-dsfr.codegouv.studio/?path=/docs/components-header--simple-header#with-uncontrolled-search-bar  
https://components.react-dsfr.codegouv.studio/?path=/docs/components-searchbar--default-uncontrolled  

Best
