### ISSUE TITLE
dsfr-charts

### ISSUE THREAD

**Issue by revolunet** [codegouvfr/react-dsfr#244]
Il existe une lib de charts dédiée DSFR : https://github.com/GouvernementFR/dsfr-chart

C'est implémenté en VueJS avec des webcomponents; 

Une idée de comment ca pourrait s'intégrer (ou pas) dans un projet react-dsfr ?

**Comment by revolunet** [comment]
Un essai ici, ça a l'air de bien fonctionner : https://stackblitz.com/edit/vitejs-vite-aqzu7b?file=src%2FApp.tsx


J'ai du faire un truc degueu, je sais pas si vous avez une meilleure idée


```jsx
const MiseryWrapper = (props) => {
  const [ready, setReady] = useState(false);
  const check = () => {
    if ('dsfr' in window && window.dsfr.colors) {
      setReady(true);
      return;
    } else {
      setTimeout(check, 50);
      console.log('check');
    }
  };
  useEffect(() => {
    console.log('io');
    if (!ready) {
      check();
    }
  }, []);

  if (!ready) {
    return null;
  }

  return props.children;
};

```

**Comment by garronej** [comment]
Ah super! 
Merci du feedback!  
Dsl de ne pas avoir rep je me suis dis que j'allais regarder mais je n'ai pas trouver le temps.  

Mais si tu as un truck qui marche ça pourais être cool de faire une page dédier sur [le site gitbook](https://react-dsfr.codegouv.studio/)!  

Qu'es que tu en pense?

**Comment by revolunet** [comment]
Yes je peux, stackblitz m'a delete mon travail mais je vais refaire 😡

**Comment by garronej** [comment]
Great thanks!

**Comment by revolunet** [comment]
Here is an example implementation https://github.com/betagouv/template/blob/main/src/components/DsFrChart.tsx

Any idea how to better handle umd ?
