### ISSUE TITLE
open Modal error

### ISSUE THREAD

**Issue by joelisayas** [codegouvfr/react-dsfr#245]
Bonjour,

l'ouverture d'une modal via le code `myModal.open()`, génère régulièrement une erreur

```
TypeError: Cannot read properties of null (reading 'modal')
at Object.open (Modal.tsx:250:1)
```

le code :

```tsx
const myModal = createModal({
  id: 'my-modal',
  isOpenedByDefault: false,
});

const MyComponent = (props: { isActive: boolean; }) => {

  const { isActive } = props;

  useEffect(() => {  
    if (isActive) {   
      myModal.open();
    }
  }, [isActive]);

return (
    <myModal.Component
      title="mon titre"
      iconId="fr-icon-user-heart-line"
    >
      <div>Texte</div>
    </myModal.Component>
  );
};
```

**Comment by joelisayas** [comment]
that's exactly the problem (not mounted in the dom).
So there is a solution ? That's our responsability ?

**Comment by garronej** [comment]
Well concreately your responsability is to make sure that whenever you call `.open()` or `.close()` the Modal component is present in your React tree.  

If you share with me you're full component and how you're using it I'll be able to tell you how you can adjust your code so this error is prevented.

**Comment by garronej** [comment]
Unfortunately I can't see anything that could lead to the error mentioned in the piece of code you shared.  

Can you share the URL of the repo alongside with some reprodution steps?

**Comment by joelisayas** [comment]
unfortunately i can't, it's a private repo.
I will try to find a solution.
Thanks for your time

**Comment by garronej** [comment]
It's probably not your call but "public money, public code", all code developped by the service public is supposed to be open source.   

Regardless, If you want you can use [the MUI modal](https://mui.com/material-ui/react-modal/).  

If you enable the [DSFR MUI integration](https://react-dsfr.codegouv.studio/mui) the look will be very similar from the original modal and it will be a better fit for a fully controlled modal.
