### ISSUE TITLE
Page storybook Range ne charge pas

### ISSUE THREAD

**Issue by totakoko** [codegouvfr/react-dsfr#252]
:wave: 
Pour info, la page storybook correspondant au composant range ne charge pas :grimacing: 
:point_right: https://components.react-dsfr.codegouv.studio/?path=/docs/components-range--default

Il semblerait y avoir une petite boucle CPU infinie.

**Comment by ddecrulle** [comment]
Salut @totakoko,

Merci d'avoir signalé ce problème. Pour l'instant, j'ai désactivé les stories qui semblent causer cette boucle CPU infinie sur la page Storybook du composant Range. 

En analysant la situation, il semble que ce problème survienne lorsque le Range utilise la propriété step. Il s'agit d'un bug du DSFR. En effet on retrouve la même chose sur la documentation officielle du composant [ici](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/curseur-range/).

Merci pour ta collaboration  !

**Comment by garronej** [comment]
Merci @totakoko pour le rapport.  

Merci Dylan le best

**Comment by totakoko** [comment]
Bien vu, j'ai pas pensé à regarder côté DSFR !
:clap:

**Comment by totakoko** [comment]
Il y a une [issue ouverte depuis janvier](https://github.com/GouvernementFR/dsfr/issues/865). :grimacing:
