### ISSUE TITLE
Component Range : la props "step" fait crasher le navigateur sur le storybook et dans l'app

### ISSUE THREAD

**Issue by ThomasDos** [codegouvfr/react-dsfr#254]
Le component `<Range />` crash lors de l'utilisation de la props `step` sur navigateur chrome et Edge (sans `step`, le component fonctionne normalement), vous pouvez facilement reproduire ce bug directement via le storybook si vous cliquer sur `Set Number` : https://components.react-dsfr.codegouv.studio/?path=/docs/components-range--default 

-----------------------

Pour reproduire -> 

Ne crash pas : 
```
        <Range
          label="Dans un rayon de"
          max={100}
          min={0}
          suffix=" km"
        />
```

Crash  : 

```
        <Range
          label="Dans un rayon de"
          max={100}
          min={0}
          step={25}
          suffix=" km"
        />
```

**Comment by revolunet** [comment]
il semblerait que cela ait été corrigé dans [ce commit sur @gouvfr/dsfr](https://github.com/GouvernementFR/dsfr/commit/4edc6732ab97f07164619954b7847c6623fbd378) en 1.11.2; Or react-dsfr utilise encore la 1.11.1

il faudrait qu'une bonne âme tente d'upgrade ici la dépendance à @gouvfr/dsfr

**Comment by revolunet** [comment]
bon apparemment ca ne suffit pas il y un truc buggy dans ce composant :/

**Comment by garronej** [comment]
> il faudrait qu'une bonne âme tente d'upgrade ici la dépendance à @gouvfr/dsfr  

Attend ça c'est trivial je te le fait tout de suite!

**Comment by garronej** [comment]
Done! @revolunet Tu sais c'est facil, il suffit juste de bump la version de @gouvfr/dsfr dans le package.json.  
Si il y a des breaking change le transpilateur CSS va donner du rouge.  

Si il y a des régression visuelle je peux les voir au niveau du storybook avec [chromatic](https://chromatic.com) en théorie. J'ai juste pas réussi a configurer Chromatique pour un projet open source.  
Ils nous on donner un accès gratuit mais je ne sais pas comment faire une sorte de ne pas leaker le token...  

Anyway

**Comment by revolunet** [comment]
Thanks @garronej 🤗
J'ai testé de bump mais j'avais un souci dans le storybook qui freeze sur le composant Range... Je reteste dans la journée

**Comment by ddecrulle** [comment]
Hello désolé j'avais pas vu ce thread, c'est un bug du dsfr il faut attendre que cette issue https://github.com/GouvernementFR/dsfr/issues/865 soit corrigée

**Comment by garronej** [comment]
Merci pour le followup

**Comment by ddecrulle** [comment]
La version 1.12.0 du dsfr corrige ce souci, disponible dans react-dsfr@1.9.20.

**Comment by revolunet** [comment]
thanks @ddecrulle 👍
