### ISSUE TITLE
Footer : sans partenaire principal, les partenaires secondaires devraient être alignés à gauche

### ISSUE THREAD

**Issue by Falinor** [codegouvfr/react-dsfr#255]
Les partenaires secondaires du Footer devraient être alignés à gauche lorsque le partenaire principal n’est pas renseigné.

Source : [design système français - pied de page](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/pied-de-page/)
> Le partenaire principal est toujours placé à gauche. Les partenaires secondaires sont placés à droite si associés à un partenaires principal, sinon à gauche.

#### Exemple
<img width="1236" alt="Screenshot 2024-04-24 at 16 39 43" src="https://github.com/codegouvfr/react-dsfr/assets/9626158/a5d4072a-35f0-4d5b-9ce9-0c62149e7db1">

**Comment by enguerranws** [comment]
I can take a look at that.

**Comment by garronej** [comment]
@enguerranws Thanks!

**Comment by enguerranws** [comment]
sorry, I'm a bit late, totally forgot this. 

Here's the PR : https://github.com/codegouvfr/react-dsfr/pull/262
