### ISSUE TITLE
SelectNext: régression placeholder toujours sélectionnable

### ISSUE THREAD

**Issue by totakoko** [codegouvfr/react-dsfr#256]
:wave: 
Je ne connais pas le but recherché de [ce commit](https://github.com/codegouvfr/react-dsfr/commit/5adb1973e560c2886616afe17676fec4bb908445), mais maintenant, tous les les attributs d'une Option ne sont pas passés au DOM (disabled et selected), notamment pour le placeholder qui est toujours sélectionnable.

Comportement en 1.9.3 : on ne peut pas sélectionner le placeholder
![image](https://github.com/codegouvfr/react-dsfr/assets/8938024/d4948210-2651-49ae-8b12-6400bdfbe74d)

Comportement en 1.9.9 : on peut sélectionner le placeholder
![image](https://github.com/codegouvfr/react-dsfr/assets/8938024/b082a067-df79-42d8-a7d7-be30d281648c)

Par ailleurs, côté DSFR natif, je vois qu'ils permettent d'utiliser un attribut hidden sur le placeholder pour qu'il n'apparaisse pas dans la liste. Est-ce que ça serait facile à implémenter ? J'imagine que ça devrait être un paramètre supplémentaire facultatif au composant.

**Comment by garronej** [comment]
@ddecrulle Tu peut regarder?  
Je savais bien qu'il y avais une subtilité dont je ne me rappelais plus 

@totakoko Merci pour l'issue
