### ISSUE TITLE
Component Range : BUG avec l'option double

### ISSUE THREAD

**Issue by pprev94** [codegouvfr/react-dsfr#259]
Le composant Range en mode double ne se comporte pas comme il devrait. En effet lorsque les deux valeurs min et max sont identiques et que l'on tire par exemple le handle de gauche vers la droite, les deux handles changent de positions mais seule le onChange de la valeur min est déclenché, c'est très gênant

**Comment by garronej** [comment]
@pprev94 merci pour le rapport.  

@lsagetlethias tu pense que c'est un bug de @gouvfr/dsfr ou que c'est a nous de corriger?

**Comment by lsagetlethias** [comment]
Le problème vient du côté du DSFR car de notre côté on forward bien les deux `nativeInputProps.onChange`. Je suppose qu'il ne déclenche pas le trigger du second `onChange` lorsque que le premier handler "pousse" le second.

![image](https://github.com/codegouvfr/react-dsfr/assets/5783789/da4716d0-bc00-4a5b-8f30-431184ebba17)

Comme le montre ce screen, même en natif le trigger ne se fait pas, uniquement la propriété `value` est mise à jour pour l'input "poussé".

Peut être il y'a des events customs de trigger mais rien ne l'indique ni dans la doc (https://www.systeme-de-design.gouv.fr/utilisation-et-organisation/developpeurs/api-javascript) ni dans le code.

**Comment by garronej** [comment]
Hello @lsagetlethias,  

Merci d'avoir regarder! Je vais faire remonter.

**Comment by ddecrulle** [comment]
La version 1.12.0 du dsfr corrige ce souci, disponible dans react-dsfr@1.9.20.
