### ISSUE TITLE
Composant MainNavigation - Mega menu - Bouton Fermer

### ISSUE THREAD

**Issue by benoit-tb** [codegouvfr/react-dsfr#261]
Bonjour,

Le bouton "Fermer" présent dans les mega menu du composant MainNavigation ne fait aucune action, contrairement à ce qui est fait dans le composant "Navigation principale" du DSFR, qui lui ferme le mega menu : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale

Une évolution est-elle prévue pour corriger cela prochainement ?

Merci

**Comment by garronej** [comment]
Good catch!  

J'ai corriger et publier une nouvelle version.  [1.9.15](https://www.npmjs.com/package/@codegouvfr/react-dsfr/v/1.9.14?activeTab=versions)

J'ai aussi coriger la story mainNavigation/megaMenu qui ouvrais le pannel au dessus:  
https://components.react-dsfr.codegouv.studio/?path=/docs/components-mainnavigation--direct-links#mega-menu

https://github.com/codegouvfr/react-dsfr/assets/6702424/594cbba7-4b91-44c1-a394-597857556811
