### ISSUE TITLE
Apparition de bordures sur les tableaux dans la version 1.9.20

### ISSUE THREAD

**Issue by loicguillois** [codegouvfr/react-dsfr#264]
Bonjour,

Suite à la publication de la version `1.9.20`, les tableaux ont une bordure de 1 pixel noire. Le rollback en `1.9.17` m'a permis de corriger le problème.

![image](https://github.com/codegouvfr/react-dsfr/assets/55890/96cb448e-adeb-4784-84f7-89445ba6832a)

**Comment by enguerranws** [comment]
Bonjour @loicguillois, 

Il semble y avoir une bordure de 2px noire en bas de la ligne d'en-tête : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/tableau 

Je ne me rappelle plus si c'était le cas avant. Par contre, on a un décalage de CSS entre la doc DSFR et le storybook (https://components.react-dsfr.codegouv.studio/?path=/docs/components-table--default).

Ce delta fait qu'il nous manque quelques règles comme : 
```
  background-position: bottom;
  background-repeat: no-repeat;
  background-size: 100% 2px;
```

J'essaie de voir d'où ça vient (montée de version côté DSFR pas encore faite côté react-dsfr, ou autre chose).

**Comment by loicguillois** [comment]
Bonjour @enguerranws ,

Je viens de voir passer ce message aujourd'hui : https://mattermost.incubateur.net/betagouv/pl/oekzspxrfjg4zqgwhyp4qcju6c

à priori il s'agirait d'une modification apportée par la version 1.12 (en date de la semaine dernière mais la communication a été faite aujourd'hui sur mattermost)

**Comment by ddecrulle** [comment]
Effectivement la seule différence entre la 1.9.17 et 1.9.20 est une montée de version dsfr (désolé j'ai été trop vite et j'ai trop bump la version)

**Comment by loicguillois** [comment]
Pas de soucis ! Ce n'était pas un bug mais une feature du coup. Je pense qu'on peut clôturer l'issue.

Merci à vous,
