### ISSUE TITLE
warning dans le composant Select

### ISSUE THREAD

**Issue by timothee-LJN** [codegouvfr/react-dsfr#265]
Le composant `Select` exporté depuis `SelectNext` modifie directement la valeur des options avec `selected: true` et cause un warning de react. 

<img width="508" alt="image" src="https://github.com/codegouvfr/react-dsfr/assets/105201321/34c4b053-10ce-4c05-9e0f-9f1835d5589c">

Ajouter `selected: undefined` dans la définition des `options` passées au composant `<Select />` ne permet pas de faire disparaitre le warning en console.

**Comment by martinratinaud** [comment]
Meme problème pour nous chez FCU

**Comment by ddecrulle** [comment]
Bonjour, vous avez un code pour reproduire ça ? 

J'ai déjà eu ce souci et je viens de regarder sur mon app, je n'ai plus le warning et je vois rien dans mon code d'explicite ...

**Comment by garronej** [comment]
Oui en effet c'est très maladroit, il faut reprender ça

**Comment by garronej** [comment]
J'ai retravailler le composant SelectNext.  
Vous pouvez tester dans la release candidate `1.9.30-rc.1` 
Je vous laisse me dire si tout marche correctement.

**Comment by garronej** [comment]
C'est disponible dans 1.9.31. Merci d'avoir fait remonter!
