### ISSUE TITLE
Button: Police non Marianne quand icone remix icone utilisée

### ISSUE THREAD

**Issue by totakoko** [codegouvfr/react-dsfr#269]
Sur un composant Button, quand j'utilise une icone DSFR, tout est bien et la police du texte est Marianne.
Par contre, si j'utilise une icone Remix Icons, alors la police est un fallback local vers Liberation Serif qui n'est pas top.
Est-ce voulu ?
L'issue est peut-être côté DSFR aussi.

- avec `iconId="fr-icon-download-line"` => ok
![2024-07-08_14-15_1](https://github.com/codegouvfr/react-dsfr/assets/8938024/9fbd991a-3760-4746-a87e-457ec54efc11)

- avec  `iconId="ri-download-2-line"` => moche
![2024-07-08_14-15](https://github.com/codegouvfr/react-dsfr/assets/8938024/980725a6-dd34-4de5-9241-5628e250743f)

**Comment by garronej** [comment]
Salut @totakoko,  
Ah mince :/  
Non c'est pas voulu, te te sens de regarder a quoi c'est dù?  
react-dsfr c'est un peut votre projet tout le monde est libre de contribuer.

**Comment by totakoko** [comment]
Je vais essayer de voir ça, je sais juste que c'est la police remixicons qui est utilisée pour le ::before (icone) et le texte directement.

**Comment by totakoko** [comment]
Ok, c'est bon. Ça venait du CSS de remixicons (2.5) qui était importé et qui n'était pas voué à être utilisé sur les boutons, mais seulement des span d'icones. Je l'ai supprimé et tout est nickel maintenant.
Désolé pour ce faux positif ! :sweat_smile: 
![image](https://github.com/codegouvfr/react-dsfr/assets/8938024/83e7df1e-aa49-4b89-9679-a3763887f702)

**Comment by garronej** [comment]
Ah bon?! C'est vrais? Mais normalement react-dsfr fait tout pour toi, tu n'a pas a importer quoi que ce soit.  
react-dsfr analise ton code au moment du build... 

https://react-dsfr.codegouv.studio/icons

**Comment by totakoko** [comment]
C'est côté FCU qu'on avait un import, pas de problème côté react-dsfr je te rassure ! https://github.com/betagouv/france-chaleur-urbaine/blob/179e349782b311cfbd72d8164f980a4a7542a942/src/pages/_app.tsx#L11

**Comment by garronej** [comment]
Ok top top top

**Comment by garronej** [comment]
Ah mais attend!  
Je vois que vous importez le CSS a la main!  
https://github.com/betagouv/france-chaleur-urbaine/blob/179e349782b311cfbd72d8164f980a4a7542a942/src/pages/_app.tsx#L7-L11  

Et je vois aussi que vous n'utilisez pas le script `only-include-used-icons`  

Dans l'utilisation standard react-dsfr grère tout pour vous!  
https://react-dsfr.codegouv.studio/ (la tab Next App router)
https://github.com/garronej/react-dsfr-next-appdir-demo  

Là vous faites plein de trucks que React-dsfr fait tout seul normalement

**Comment by garronej** [comment]
Là c'est vraiment bête, vous n'utiliser pas du tout l'adapter `@codegouvfr/react-dsfr/next-pagesdir` pour Next.js Pages Router.  
Vous ne profitez pas des meilleurs performances et de la meilleur DX...

**Comment by totakoko** [comment]
Hm, oui, alors je pense que c'est parce que tu regardes le code actuel et non la PR de migration (car on a beaucoup de changements...) de @dataesr vers @codegouv. Après si tu as toujours des conseils on est preneurs !

[Le même fichier sur la nouvelle PR](https://github.com/betagouv/france-chaleur-urbaine/blob/migrate_to_codegouvfr_react_dsfr/src/pages/_app.tsx)

**Comment by garronej** [comment]
Ah ok magnifique! Non vous m'avez l'air tout bon!  
Oui je comprend, vous avez transitioner j'aurais du me douter en voyant l'historique du projet!
