### ISSUE TITLE
Accordion: when I open it, I only see part of its content.

### ISSUE THREAD

**Issue by GillesFONO-saegus** [codegouvfr/react-dsfr#270]
In my code, I have an accordion that contains a nested div which constitutes the content I want to display. It used to work quite well before, but now I can only see part of this content, approximately 24px of the whole content. The rest is cropped.

**Comment by garronej** [comment]
Hello @GillesFONO-saegus,  

What version of react-dsfr introduced this bug?

**Comment by GillesFONO-saegus** [comment]
I have this version : "@codegouvfr/react-dsfr": "^1.9.8",

**Comment by garronej** [comment]
Yes but you said it worked before? With what version did it started to break?

**Comment by GillesFONO-saegus** [comment]
I start to break with 1.9.8 i think.

**Comment by garronej** [comment]
And it worked with 1.9.7 ?

**Comment by GillesFONO-saegus** [comment]
I work with Docker and I just tried to start it without Docker on version 1.9.8, and it works.

**Comment by GillesFONO-saegus** [comment]
I don't know why but i think it is my docker container the problem. I will investigate the problem. Thanks for your answers
