### ISSUE TITLE
PasswordInput + DSFR JS = 💔

### ISSUE THREAD

**Issue by revolunet** [codegouvfr/react-dsfr#272]
While the `PasswordInput` works correcly in the [storybook demo](https://components.react-dsfr.codegouv.studio/?path=/docs/blocks-passwordinput--default), the behaviour is buggy on [this basic example](https://stackblitz.com/edit/nextjs-tsfl7d?file=app%2Flayout.tsx,app%2Fpage.tsx,package.json).

Look like there is some react integration issues with the ["native" DSFR JS here](https://github.com/GouvernementFR/dsfr/blob/main/src/component/password/script/password/password-input.js#L18).

Indeed, when the component rerenders, it sets back the `type` to `password` as its not aware of DSFR DOM edits...

I'm thinking about reimplementing the toggle logic in the react-dsfr component.... WDYT ?

**Comment by garronej** [comment]
Hey @revolunet,  

Let's maybe just make to component `"use client";` what do you think?
I've released @codegouvfr/react-dsfr@1.9.26-rc.0 so you can try it out.

**Comment by revolunet** [comment]
Still same issue : https://stackblitz.com/edit/nextjs-tsfl7d?file=app%2Flayout.tsx,app%2Fpage.tsx,package.json

**Comment by revolunet** [comment]
Perfect thanks Sir 🙏
