### ISSUE TITLE
Régression style fr-input

### ISSUE THREAD

**Issue by totakoko** [codegouvfr/react-dsfr#276]
:boom: Il semblerait que la PR #274 ait déclenché une régression de notre côté.

On utilise Formik qui [passe automatiquement des propriétés au composant Input dont className](https://github.com/jaredpalmer/formik/blob/c798145e2307b0273ea4d9c6bfd8250f28d95be9/packages/formik/src/Field.tsx#L202-L232) ce qui fait que la classe fr-input et les classes de validation sautent.

Problème visible [ici](https://france-chaleur-urbaine-dev-pr739.osc-fr1.scalingo.io/) : il faut faire un test d'adresse pour afficher le formulaire qui pose problème.

J'ai pas le temps de regarder pour un correctif ce soir donc ça attendra la semaine prochaine au minimum.  Et aussi je ne connais pas le cas d'usage pour lequel a été créé la PR... :shrug: 

Un avis ? Est-ce que l'objectif de la PR était de surcharger complètement className par exemple ou juste d'ajouter des classes ?

**Comment by ddecrulle** [comment]
Hello, l'objectif de la PR et surtout de pouvoir surcharger `aria-describedby`. J'ai eu la même regression que tu mentionnes, que j'ai corrigé [ici](https://github.com/InseeFr/Lunatic-DSFR/commit/f944e7675cecd1dff28844fa248c1292f32e5e18). 

Deux solutions, soit tu retires le className des props passées par Formik comme j'ai fais, soit on considère qu'il n'est jamais nécessaire de changer le classname (de retirer `"fr-select"`, `"fr-input"`, etc), et dans ce cas là on applique le `className` après avoir spread les nativeProps.

**Comment by totakoko** [comment]
Pour les props passées par Formik, on ne passe aucune class, c'est Formik qui passe className, même si c'est undefined. Et je suis pas sûr de vouloir modifier Formik là... :upside_down_face: 
Je serais d'avis de déplacer le className après les nativeInputProps pour conserver la gestion des classes par le formulaire (à moins que ça gène des personnes...)

**Comment by ddecrulle** [comment]
Il ne s'agit pas de modifier Formik ... simplement enlever le className des props générées par Formik.  

Si je reprend ton code c'est quelque chose comme ça : 

```diff
- const field = formik.getFieldProps({ name, ...props });
+ const {className, ...field } = formik.getFieldProps({ name, ...props });
```
