### ISSUE TITLE
Probleme dans l'utilisation du Header

### ISSUE THREAD

**Issue by martinratinaud** [codegouvfr/react-dsfr#286]
Bonjour à tous

j'ai ce message d'erreur

```
dsfr : HeaderLinks # -  header__tools-links content is different from header__menu-links content.As you're using a dynamic framework, you should handle duplication of this content yourself, please refer to documentation:https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete 
```

dans [ce fichier](https://github.com/betagouv/france-chaleur-urbaine/blob/migrate_to_codegouvfr_react_dsfr/src/components/shared/page/SimplePage.tsx) (nous sommes en pleine migration  vers react-dsfr

J'ai eu beau cherché dans la doc, je n'ai pas compris comment résoudre ce problème

Merci pour votre aide

**Comment by garronej** [comment]
Salut @martinratinaud,  

Je crois que c'est un problème interne du DSFR, il faut que je regarde.  
@revolunet @enguerranws on a déjà vu çe problème non? Qu'es que vous pensez qu'il faut faire?

**Comment by totakoko** [comment]
Le warning est [côté DSFR](https://github.com/GouvernementFR/dsfr/blob/fe9d66b4ccaa7c3a3c0cb07eca69ddd6787965c4/src/component/header/script/header/header-links.js#L41-L43), quand toolsHtmlDuplicateId != menuHtml.
Voici les valeurs pour notre cas :
```html
// toolsHtmlDuplicateId = 
<ul class="fr-btns-group"><li><a id="fr-header-quick-access-item--Espacegestionnaire-0-mobile" class="fr-btn fr-icon-account-circle-line" href="/connexion">Espace gestionnaire</a></li></ul>
// menuHtml = 
<ul class="fr-btns-group"><li><a id="fr-header-quick-access-item--Espacegestionnaire_mobile-0" class="fr-btn fr-icon-account-circle-line" href="/connexion">Espace gestionnaire</a></li></ul>
```

Donc on a un suffixe d'id qui vaut `-0-mobile` et sinon `_mobile-0`, donc ça ne doit pas être grand chose à corriger j'imagine. :detective:

**Comment by garronej** [comment]
Lovely! oui je devrais pouvoir corriger ça!  Merci pour le rapport détailé.

**Comment by garronej** [comment]
Je m'occupe de ça

**Comment by garronej** [comment]
Fixed

**Comment by garronej** [comment]
Actually fixed now
