### ISSUE TITLE
Display toggle switch when label is null or empty

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#289]
This is a side effect of #275 similar to the one reported on checkboxes (#281).

We use toggle switches with an empty label in a table, in order not to repeat the information in the column head.
Although this probably is a very poorly designed use case for toggle switches, this may benefit a partial revert like it has been done for checkboxes. I let you decide @ddecrulle.

Checkboxes and toggle switches seem to be the only 2 impacted components that rely on the label for display purposes.

Of course the quick an dirty whitespace workaround does the job.

**Comment by ddecrulle** [comment]
Yes sorry for that, It's really annoying that it's absolutely need the `<label>`, even if it's empty, for the style to be correct. I reverted the PR on Switch component.
