### ISSUE TITLE
Customize locale storage key for analitycs

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#302]
We are building an app with multiple technical components. A React App, a Vue App, an eleventy static site... all living under the same domain name.

If a visitor gives or withdraw its consent for data collection on one of the component and then visit another component, he shouldn't be prompted again for consent.

So we would like to make the localStorageKeyPrefix a param here  in order to use a custom name that doesn't contain "@codegouvfr/react-dsfr" : https://github.com/codegouvfr/react-dsfr/blob/main/src/consentManagement/createConsentManagement.ts#L12

```ts
export const localStorageKeyPrefix = "@codegouvfr/react-dsfr finalityConsent";
````

NB : the light or dark color scheme is also a "shared" local storage element, but it's name is simpler. It's just "scheme". So we are fine with it. But it could be customized too.

**Comment by garronej** [comment]
Hello @slafayIGN,  

Ok I guess I could make a parameter for this even though it's very specific to your usecase.  

From a library user perspective, what I do when I need a very specific change is using [patch-package](https://www.npmjs.com/package/patch-package).  
This enables me to make whatever little changes I need to a library in a matter of minutes. It's quicker than waiting for the upstream to implement the change.

**Comment by slafayIGN** [comment]
Thanks @ocruze and @garronej for the change 👍
