### ISSUE TITLE
Proposition d'ajout d'un `info` sur l'input

### ISSUE THREAD

**Issue by maxgfr** [codegouvfr/react-dsfr#306]
Hello, 

Je voulais avoir votre avis sur la possibilité d'ajouter au sein de l'[`Input`](https://github.com/codegouvfr/react-dsfr/blob/main/src/Input.tsx) un point information, car actuellement, on a juste le success et l'error

<img width="543" alt="Screenshot 2024-09-12 at 15 08 51" src="https://github.com/user-attachments/assets/9c134871-b148-456b-9fe7-9acf0d60047c">

De mon côté, je sais que cela peut créer le débat, et que ce feature peut sortir du scope de l'Input, d'où le fait que j'ouvre l'issue pour avoir votre avis.

D'ailleurs, quid de la gouvernence sur l'ajout de ce genre de feature ? Je suppose qu'il faut peser le pour et le contre afin que les composants ne fassent pas tout et n'importe quoi

**Comment by garronej** [comment]
Thank for the suggestion, I implemented it:  

![Uploading image.png…]()

**Comment by martinratinaud** [comment]
Salut
Je suis interessé par cette feature mais je la vois pas dans la 1.13.6 ?

**Comment by ddecrulle** [comment]
Salut, elle est pourtant bien présente [cf](https://github.com/codegouvfr/react-dsfr/blob/v1.13.6/src/Input.tsx#L35). Tu as un snippet de code qui ne fonctionne pas ?

**Comment by martinratinaud** [comment]
Salut

Alors moi quand je regarde dans mes node_modules avec cette version installée, j'ai

```
import React, { type ReactNode, type CSSProperties, type ComponentProps } from "react";
export type FieldsetProps = FieldsetProps.Radio | FieldsetProps.Checkbox;
export declare namespace FieldsetProps {
    type Common = {
        className?: string;
        id?: string;
        classes?: Partial<Record<"root" | "legend" | "content" | "inputGroup", string>>;
        style?: CSSProperties;
        legend?: ReactNode;
        hintText?: ReactNode;
        options: {
            label: ReactNode;
            hintText?: ReactNode;
            nativeInputProps: ComponentProps<"input">;
        }[];
        /** Default: "vertical" */
        orientation?: "vertical" | "horizontal";
        /** Default: "default" */
        state?: "success" | "error" | "default";
        /**
         * The message won't be displayed if state is "default".
         * If the state is "error" providing a message is mandatory
         **/
        stateRelatedMessage?: ReactNode;
        /** Default: false */
        disabled?: boolean;
        /** default: false */
        small?: boolean;
    };
    type Radio = Omit<Common, "options"> & {
        type: "radio";
        name?: string;
        options: (Common["options"][number] & {
            illustration?: ReactNode;
        })[];
    };
    type Checkbox = Common & {
        type: "checkbox";
        name?: never;
    };
}
/** @see <https://components.react-dsfr.codegouv.studio/?path=/docs/components-radiobutton> */
export declare const Fieldset: React.MemoExoticComponent<React.ForwardRefExoticComponent<FieldsetProps & React.RefAttributes<HTMLFieldSetElement>>>;
export default Fieldset;
```

Donc j'imagine qu'il ya un pb de build

**Comment by ddecrulle** [comment]
La fonctionnalité a été ajoutée sur le champ de saisie classique, l'Input, pas sur les radios et checkbox.

**Comment by martinratinaud** [comment]
Ah my bad sorry

**Comment by ddecrulle** [comment]
En parcourant le figma DSFR, je n'ai pas vu cette feature ailleurs que sur l'input.

**Comment by martinratinaud** [comment]
Ok, dommage

**Comment by garronej** [comment]
Merci @ddecrulle pour être aller regarder!
