### ISSUE TITLE
[Accessibilité] - Champ de saisie (aria-live="assertive")

### ISSUE THREAD

**Issue by Destinyyyy** [codegouvfr/react-dsfr#311]
Hello,

Suite à des retours concernant un audit d'accessibilité, nous nous sommes rendu compte que le composant champ de saisie [Input](https://components.react-dsfr.codegouv.studio/?path=/docs/components-input--default) ne possédait pas d'attribut aria-live="assertive" pour le message d'erreur.

Il semble manquer un élément dédié aux lecteurs d'écran pour le composant Input, afin d'être en conformité avec le DSFR et l'accessibilité (source : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/champ-de-saisie en fin de page).

Cet élément est bien présent pour le composant [RadioButtons](https://components.react-dsfr.codegouv.studio/?path=/docs/components-radiobuttons--default)

**Comment by garronej** [comment]
Bonjour @Destinyyyy,  

Vous vous sentez de faire une PR pour ça?

**Comment by Destinyyyy** [comment]
Hello @garronej  yes, j'essayerais de faire ça en début de semaine prochaine !

**Comment by garronej** [comment]
Super merci!
