### ISSUE TITLE
ConsentManagement: site crashes while visiting personal data policy page from consent management modal

### ISSUE THREAD

**Issue by ocruze** [codegouvfr/react-dsfr#317]
Hi,
I'm not sure if it's caused by react-dsfr or by the base dsfr library (or maybe I'm doing something wrong), but what happens is: if I try to visit the personal data policy page, the site crashes 
![image](https://github.com/user-attachments/assets/ea8a8610-9519-45bc-bfde-ab5f93198f5f)

![image](https://github.com/user-attachments/assets/5527884e-f5ec-4bd1-a5d6-ac9140fe7776)

The crash seems to occur at line 4682 of dsfr.module.js:
![image](https://github.com/user-attachments/assets/14dad7fd-6674-4403-aa13-ee7feb04f2eb)

This is how I'm creating the consent manager :
```ts
createConsentManagement({
  personalDataPolicyLinkProps: routes.personal_data().link // type-route
})
```

Temporarily, I've changed it to `personalDataPolicyLinkProps: { href: routes.personal_data().href }`, but it would be nice to be able to fix the error. Any idea how to solve it?

**Comment by garronej** [comment]
Hello @ocruze,  

Can we have a repo?

**Comment by ocruze** [comment]
Ok actually, I'm unable to reproduce the error with neither vite nor cra. There must be something wrong with my project (with webpack). So, I'll close the issue, I'll reopen it if I have something new to share.
