### ISSUE TITLE
Icon in main navigation

### ISSUE THREAD

**Issue by zelytra** [codegouvfr/react-dsfr#320]
Is it possible to replace the text in the [main navigation](https://components.react-dsfr.codegouv.studio/?path=/docs/components-mainnavigation--direct-links) component by an icon ? 
Like having a bell for the notificaiton page within the navigation bar ?
Or is this not acessibility friendly this feature ?

**Comment by enguerranws** [comment]
```
export namespace Item {
        export type Common = {
            isActive?: boolean;
            className?: string;
            text: ReactNode;
        };
        ...
```
You surely can insert an icon in the navigation items.

However, [that case is not documented](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/navigation-principale), and the DSFR team only describe use cases with text. Be sure to run an accessibility tool to check your implementation if you want to do so.
