### ISSUE TITLE
Sommaire avec plusieurs niveaux de titres

### ISSUE THREAD

**Issue by slafayIGN** [codegouvfr/react-dsfr#330]
Bonjour,

Le composant Summary propose aujourd'hui un tableau de liens "à plat" et ne peut donc avoir qu'un seul niveau de profondeur.

https://github.com/codegouvfr/react-dsfr/blob/a93fccde519b099bda7b72ba2020840523f75026/src/Summary.tsx#L16-L19

La [documentation DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/sommaire) du composant permet d'avoir plusieurs niveaux hiérarchiques (sans préciser la profondeur possible il me semble)

![image](https://github.com/user-attachments/assets/6cdafd31-d43b-48be-9049-5ba969d1b21e)

Une évolutions du composant serait bienvenue.

**Comment by garronej** [comment]
DONE thx for reporting

**Comment by slafayIGN** [comment]
👍 Merci @maximallain et @garronej
