### ISSUE TITLE
How can you toggle off Controlled Search Input programmatically ?

### ISSUE THREAD

**Issue by arnaudambro** [codegouvfr/react-dsfr#332]
Hello

For this component
https://components.react-dsfr.codegouv.studio/?path=/story/components-searchbar--with-controlled-input

How would you turn it off programmatically ? 
is there a better way than calling the "Fermer" button through `document.getElement...` ?
<img width="530" alt="image" src="https://github.com/user-attachments/assets/c3339c76-8c92-4617-9e33-010e8e276cb6">

**Comment by garronej** [comment]
hello @arnaudambro,  

I'm sorry I don't see what you are reffering to...

**Comment by arnaudambro** [comment]
no worries, I just did it and it works well

https://github.com/betagouv/zacharie/blob/5e97de116f96b34cf3cc150dd642878f5f8ac66c/app/app/components/SearchInput.tsx#L27

```
      document.getElementById("fr-header-header-with-quick-access-items-search-button")?.click();
```

**Comment by ddecrulle** [comment]
If I may, it’s not ideal to directly manipulate the document in a React app, as React manages the Virtual DOM. It’s always better to use a hook like useRef or useState to interact with the DOM in a React-friendly way.

Regarding your “Fermer” button, I’m not entirely sure what its purpose is. If it serves the same function as the native “clear” icon for an input, you can simply reset the value of the input, which is very easy if the input is controlled.
