### ISSUE TITLE
Utilisation de useStyles

### ISSUE THREAD

**Issue by l-vincent-l** [codegouvfr/react-dsfr#336]
Dans la documentation de [CSS in JS](https://react-dsfr.codegouv.studio/css-in-js) il y a deux fonctions `useStyles` d’utiliser, une provient directement de TSS, et une provient de `tss-react/dsfr`.

Je me demandais quand est-ce qu’il fallait utiliser l’une plutôt que l’autre ? Les deux ont l’air utiliser dans le code de ce dépôt.

**Comment by garronej** [comment]
C'est corrigé.  

Si vous utiliser MUI vous pouvez importer avec `import { } from "tss-react/mui"`  vous aurez l'objet theme:  

```ts
const { theme /* objet theme de mui */ } = useStyles();
```

**Comment by garronej** [comment]
Et si vous voulez ajouter des valeurs contextuelle utile a l'écriture de vos style vous pouvez crée votre propre ficher `src/tss.ts`

Un example:  

`src/tss.ts`
```ts
import { createTss } from "tss-react";
import { useTheme } from "@mui/material/styles";
import { useIsDark } from "@codegouvfr/react-dsfr/useIsDark";

function useContext(){
    const muiTheme = useTheme();
    const { isDark } = useIsDark();
   const someOtherValue= "foo";
   return { muiTheme, isDark, someOtherValue };
}

export const { tss } = createTss({ useContext });

export const useStyles = tss.create({});
```

And after, in your component you can import from your tss file:  

```tsx
import { tss } from "tss";

type Props= {
    className?: string;
};

export function MyComponent(props){

    const { className } = props;

    const { cx, classes, /* muiTheme, isDark, someOtherValue */ } = useStyles();
    
    return <div className={cx(classes.root, className)}>{/* ... */}</div>

}

const useStyles = tss
    .withName("MyComponent")
   .create(({ muiTheme, isDark, someOtherValue })=>({
       root: { /* ... */ }
   }));
```

It's the approach I recommend since it let you make available exactly what you need to write your styles.
