### ISSUE TITLE
Impossible to disable Card

### ISSUE THREAD

**Issue by Viczei** [codegouvfr/react-dsfr#339]
When trying to disable my Card using this parameter:
```
linkProps={{
  href: undefined,
  "aria-disabled": disabled,
}}
```
I receive an error message:
```
Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead.
    at Array.forEach (<anonymous>)
```

**Comment by garronej** [comment]
Hello @Viczei,  

The thing is that anything regarding to routing isn't handled by react-dsfr but by your routing solution of choice.  
This is something that is often missunderstood but in order for react-dsfr to work with any meta framework it has to be that way. We cannot simply use `<a />` elements, it would trigger a full reload of the website on each navigation.  

I'm happy to provide guidance but you have to tell me more about what routing solution you are using.  
See: https://react-dsfr.codegouv.studio/routing  

Example: Vite/react-router, create-react-app/type-route, Next/App router...

**Comment by garronej** [comment]
Mais de tout manière, apparement le DSFR ne permet pas d'avoir une carte désactiver.  

https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/carte  

Il faut donc customiser le composant.  

https://react-dsfr.codegouv.studio/components

**Comment by garronej** [comment]
If you want to customize the card component so that it has a disabled state you can do the following for example:  

```tsx

import { Card, type CardProps } from "@codegouvfr/react-dsfr/Card";
import { tss } from "tss-react";
import { fr } from "@codegouvfr/react-dsfr";

type Props = CardProps & {
    disabled?: boolean;
};

export function CustomCard(props: Props){

    const { disabled = false, ...rest } = props;

    const { classes } = useStyles({ disabled });

    return (
        <Card
            classes={{
                root: classes.root,
                title: classes.title,
                img: classes.img,
            }}
            {...rest}
        />
    );

}

const useStyles = tss
  .withName({ CustomCard })
  .withParams<{ disabled: boolean }>()
  .create(({ disabled }) => ({
    root: {
      "& a": {
        pointerEvents: disabled ? "none" : undefined,
      },
      "&:hover": {
        backgroundColor: disabled ? "unset" : undefined,
      },
    },
    img: {
      filter: disabled ? "grayscale(100%)" : undefined,
    },
    title: {
      "&& a": {
        color: disabled
          ? fr.colors.decisions.text.disabled.grey.default
          : undefined,
      },
    },
  }));
```


https://github.com/user-attachments/assets/8125b52f-3006-4aa3-9eb7-d9b62bbcfa38
