### ISSUE TITLE
Le contenu de la modale se trouve dans le DOM même quand celle-ci n'est pas ouverte

### ISSUE THREAD

**Issue by martinratinaud** [codegouvfr/react-dsfr#346]
Pour le site de [FCU](https://france-chaleur-urbaine.beta.gouv.fr), nous utilisons le DSFR et après un audit SEO, nous nous rendons compte que sur la page d'accueil nous avons 3 h1

- 1 est celui de la modale de consentement
- 1 est celui lié au changement de theme (cf #345)
- 1 est mon h1

En revoyant le code de la Modal, il semble que [celle-ci soient dans le DOM meme quand elle n'est pas affichée](https://github.com/codegouvfr/react-dsfr/blob/99a594d6d83dc163f49390f343c700097815687b/src/Modal/Modal.tsx#L62)

Cela fait que le DOM par exemple de la modale de consentement est toujours dans le DOM, meme si on a déjà accepté les cookies.

J'ai l'impression que cela ne devrait pas etre le cas.

**Comment by ddecrulle** [comment]
Bonjour,

Il est normal que le code de la modal soit toujours présent dans le DOM dès lors qu’elle peut potentiellement s’afficher. En effet, cela évite de recréer un élément dans le DOM à chaque fois que la modal s’affiche.

Dans ton cas, puisque tu n’as pas de mode sombre et que la modal ne peut pas s’afficher, il est pertinent de ne pas la charger dans le DOM, comme l’a mentionné @garronej. Je vais ajouter une option dans le header pour la désactiver.

Concernant la modal de consentement, je pense que la solution se trouve du côté du DSFR, notamment en ce qui concerne l’utilisation du h1 dans cette modal.
