### ISSUE TITLE
System color scheme keeps the original color forever

### ISSUE THREAD

**Issue by PlugNPush** [codegouvfr/react-dsfr#347]
https://github.com/codegouvfr/react-dsfr/blob/fcc1fe8b51e0946252121834e400efb6151e77fd/src/useIsDark/client.ts#L69

The color scheme saved in the localStorage after calling startReactDsfr({ defaultColorScheme: "system" }) is not system but rather the color scheme that was effective at the first website launch. 

This is an unexpected behavior, I would expect the localStorage to save the "system" value instead, as it works as intended when changed manually to it.

If the system was dark on first launch, and then switches to light, the current localStorage value (dark) prevents the light theme to appear, despite choosing system as the default color scheme.

**Comment by garronej** [comment]
Hello @PlugNPush,

It's a bit more complex than that.  
The line you're referring to isn't the one that sets the enabled color scheme. The color scheme is set [in `@gouvfr/dsfr`](https://github.com/GouvernementFR/dsfr/blob/fe9d66b4ccaa7c3a3c0cb07eca69ddd6787965c4/src/scheme/script/scheme/scheme.js#L110).

> "Rather, the color scheme that was effective at the first website launch."

Actually, it's always the color scheme in which the app is currently being rendered, either `light` or `dark`.

> "This is unexpected behavior."

Everything is working as expected, but I understand why this might seem confusing.  
Your website was previously using `startReactDsfr({ defaultColorScheme: "light" })`, and now you've switched to `startReactDsfr({ defaultColorScheme: "system" })`. However, for users who had already visited your site before this change, the site will still render in light mode unless they manually switch to dark mode.

What you'd like is for DSFR to automatically detect the change from "light" to "system" in the website configuration and reset the persisted preference for existing users in such cases.  
This can be done, and it's a relevant request. It's not clear for devs why their changes doesn't seem to take effect unless they clear their cache.

Just to clarify, this is a feature request, not a bug.

**Comment by garronej** [comment]
It's implemented in the latest release

**Comment by PlugNPush** [comment]
To clarify, I never accessed the website using "light" as the colorScheme. In fact, even if I remove all website cache/storage, with "system" as the colorScheme, the issue persists -- even after your implementation. I ended up fixing this myself by adding a React effect on a top level component to overwrite "light"/"dark" being written by this module:
`localStorage.setItem('scheme', 'system');`
It works great like that.

**Comment by garronej** [comment]
Hello @PlugNPush,

It seems that `react-dsfr` might not be set up properly in your codebase.

Do you call `starDsfr()` anywhere? What meta framework are you using? Vite, Next.js?

If you could share your project, I'd be happy to pinpoint the issue.

I highly recommend addressing this now. Even if the color scheme issue is resolved for now, you're likely to encounter other problems down the road.

**Comment by PlugNPush** [comment]
I am using Vite. The only place where I initialize the DSFR is in my index.tsx file:

```
import { startReactDsfr } from "@codegouvfr/react-dsfr/spa";
import '@mui/material/styles/styled';
import '@src/styles/index.scss';
import "@codegouvfr/react-dsfr/main.css";

startReactDsfr({ defaultColorScheme: "system" });
```

The project is not yet hosted on a public repository. Is there a specific part you would like to see?

**Comment by garronej** [comment]
Can you email me the project as a zip at joseph.garrone@code.gouv.fr ?

**Comment by PlugNPush** [comment]
I just sent you the zip through Tchap, it is easier than email

**Comment by garronej** [comment]
Thank you for the upload; I understand the issue now!  

There’s nothing wrong with your setup—I simply misunderstood the issue. What you want is for the system's color scheme preference to be reflected across page reloads, even if it changes. This is indeed the expected behavior. I initially thought the user’s system preference was static, but on macOS, it can be set to "Auto" and change based on the time of day, so it's important to account for that.

Thanks for bringing this up; it’s been addressed in the latest release.

https://github.com/user-attachments/assets/14cb1ef7-75ae-49dc-aaec-0b4b48b1708e

**Comment by PlugNPush** [comment]
When "system" is set manually in the localStorage, you do not even have to reload the page to notice the change:
[Capture vidéo du 2024-12-10 18-39-01.webm](https://github.com/user-attachments/assets/0a22bb3a-c6e6-4c8a-9dfa-b2abe91a4f34)

**Comment by garronej** [comment]
Allright, I've released an update that enalbes the scheme to changes when the os preferences change without requiring a reload of the page.

**Comment by PlugNPush** [comment]
Thank you for the fix, it works as intended now!
