### ISSUE TITLE
Support of button attributes on MainNavigation

### ISSUE THREAD

**Issue by enguerranws** [codegouvfr/react-dsfr#38]
On MainNavigation component, a navigation item is rendered as a `<Link>` element if `linkProps` has been set, otherwise, it's rendered as a `<button>`. 

The use case is that we use id attribute (tracking, e2e testing, etc.). It's possible on items using linkProps, but not if linkProps is not used.

```tsx
{
      text: "Nav item as <button>",
      isActive: isNavItemActive,
      //id: "not-working-id",
      menuLinks: [
        {
          text: "Sub nav item",
          linkProps: {
            ...routes.myRoute().link,
            id: "my-working-link-id",
          }
        },
```

Should we add a `buttonProps` in `MainNavigationProps.Item` that satisfies `React.HTMLProps<HTMLButtonElement>` ?

**Comment by garronej** [comment]
Désoler @enguerranws, je vais me pencher sur cette question, je suis juste encore la tête sous l'eau avec le support de l'AppDir de Next 13

**Comment by garronej** [comment]
@enguerranws Agreed,  

It's in: https://github.com/codegouvfr/react-dsfr/commit/cc16b8138a1cab42d9e6851b7137adbfdbe1d1b9  

Thanks for the suggestion.
