### ISSUE TITLE
MUI portability

### ISSUE THREAD

**Issue by Fen747** [codegouvfr/react-dsfr#4]
Hi,

I'm currently working for the DINUM's Rizomo project, where we currently use MUI. We are considering using the DSFR as soon as possible, and therefore are interested to know more about it and where it stands in your current Roadmap ?

Thank you

**Comment by garronej** [comment]
Hi @Fen747,  

I'm currently working on this right now.  
The MUI theme adapter is almost done.  
I'currently completing mapping the spacing.  

I advise you to wait a few days before starting using it, though.  
My good UX designer college, @marchufschmitt, is abou to join the team, I'm waiting for him to do its magic with the color and typography mapping.  
If all goes according to plan the MUI component should look like legit DSFR component out of the box 🤩  

I'll ping you as soon as it's ready.  

PS: Keep in mind that the MUI integration isn't endorsed nor approved by the core DSFR team!  
Official components should always be preferred over the MUI's ones.

**Comment by garronej** [comment]
Hi @Fen747,  
Thanks for reaching out,  
To add on top of what @bzg just said,  

**Specifically about the MUI integration**:   
> Keep in mind that the MUI integration isn't endorsed nor approved by the core DSFR team!  
> Official components should always be preferred over the MUI's ones.  
I'm currently working on this right now.  
The MUI theme adapter is almost done.  
I'currently completing mapping the spacing.  
I advise you to wait a few days before starting using it, though.  
My good UX designer college, @marchufschmitt, is abou to join the team, I'm waiting for him to do its magic with the color and typography mapping.  
If all goes according to plan the MUI component should look like legit DSFR component out of the box 🤩  

I'll ping you as soon as it's ready.  

But as @bzg said, as of now, this module does not provide any of the 42 official components.  
It just provides tooling to integrates in well-established frameworks and utilities for using the DSFR fundamentals (color, spacing, typography, breakpoints) with CSS in JS solution.  
If you are looking for, components please use https://github.com/dataesr/react-dsfr instead. It's the more usable solution as of today.

**Comment by bzg** [comment]
Oh! @garronej was quicker than me :) 

About this:

> PS: Keep in mind that the MUI integration isn't endorsed nor approved by the core DSFR team!

Still, we had a fruitful discussion with the DSFR team and they are of course interesting in listing officially supported libraries, and `codegouvfr/react-dsfr` will certainly be one of them.

**Comment by garronej** [comment]
https://user-images.githubusercontent.com/6702424/204353935-ad43532b-5dde-41e1-bb08-0ac70a730a6e.mov

**Comment by bzg** [comment]
<3 the atmosphere of the video, reminds me of https://www.youtube.com/watch?v=Tj-GZJhfBmI :)

**Comment by garronej** [comment]
Mais oui, en plus il y a le coté obscur de la force!

**Comment by garronej** [comment]
Si non j'ai fait un tuto un peut plus traditionelle (pour Next.js, les SPA pas besoin de tuto c'est facil ) https://www.youtube.com/watch?v=0n0S6PcyG28&t=727s

**Comment by bzg** [comment]
Nous devons avancer sur l'utilisation de https://tube.numerique.gouv.fr pour la publication de vidéos liées à nos tâches.

**Comment by garronej** [comment]
[Screen Recording 2022-12-02 at 19.04.28-vp9-chrome.webm](https://user-images.githubusercontent.com/6702424/205410874-16af7b6b-0520-40af-ac38-6c6fddec663a.webm)

Marc a fait du super boulot. Je ferme mtn.  

https://react-dsfr.etalab.studio/mui

**Comment by bzg** [comment]
Super boulot indeed, merci beaucoup !
