### ISSUE TITLE
Add a french version of the README

### ISSUE THREAD

**Issue by bzg** [codegouvfr/react-dsfr#44]
I suggest having `README.fr.md` on top of the default `README.md`, providing at the least the basic information on what this library does and how to use it.

Maintaining translations is hard, so I would not make it mandatory to have the same content in both `README.fr.md` and `README.md`: if each file is useful, that's good enough.

**Comment by garronej** [comment]
D'accord oui, je m'en charge au jour d'hui

**Comment by garronej** [comment]
Done: https://github.com/codegouvfr/react-dsfr/blob/main/README.fr.md

**Comment by bzg** [comment]
> Done: https://github.com/codegouvfr/react-dsfr/blob/main/README.fr.md

Top, merci beaucoup !
