### ISSUE TITLE
Add a publiccode.yml

### ISSUE THREAD

**Issue by bzg** [codegouvfr/react-dsfr#45]
See https://publiccode-editor.etalab.studio - also cc @hjonin.

In particular, keep track of repositories and/or projects using @codegouvfr/react-dsfr is important to justify spending more energy in it.

PS: The way repos with `publiccode.yml` are promoting on code.gouv.fr is buggy right now, but I'll fix it.

**Comment by garronej** [comment]
Tu as raison, c'est important. Je m'en charge au jour d'hui même

**Comment by garronej** [comment]
Done: https://github.com/codegouvfr/react-dsfr/blob/main/publiccode.yml

**Comment by bzg** [comment]
> Done: https://github.com/codegouvfr/react-dsfr/blob/main/ publiccode.yml

Vu, merci !
