### ISSUE TITLE
Question : Why did you not use React.forwardRef() ?

### ISSUE THREAD

**Issue by bricejar** [codegouvfr/react-dsfr#52]
Hello,

I am confused, why don't you use React.forwardRef for some components like `<Button>`, what is the explanation of this decision ?

**Comment by garronej** [comment]
Hi @bricejar,  
Funny you ask, I just removed all use of `forwardRef` just yesterday: [see commit](https://github.com/codegouvfr/react-dsfr/commit/b4c07dba7d0e6232b90b7cf68dee3be022199bc4).   
I figgured out that the `ref` could just be an optional prop on every component. No need to `forwardRef`.  

https://stackoverflow.com/questions/62931216/why-exactly-do-we-need-react-forwardref

**Comment by bricejar** [comment]
I tried this: 
```tsx

import React, { ForwardedRef } from "react";

function Test({ ref }: { ref?: ForwardedRef<HTMLDivElement> }) {
  return <div ref={ref}>Test</div>;
}

export default function App() {
  const ref = React.useRef<HTMLDivElement>(null);

  return (
    <div className="App">
      <Test ref={ref}></Test>
    </div>
  );
}

```

And I am getting this warning, 

![image](https://user-images.githubusercontent.com/45051524/214208224-b9f5f314-d155-4419-a883-abcfb599e766.png)

Why does it work in your case ?

**Comment by garronej** [comment]
Oh gosh, my Bad!
I'll rollback to using fotwardRef asap.

Thanks for reporting!

**Comment by garronej** [comment]
I just rollded back to using `forwardRef` everywhere.
