### ISSUE TITLE
The select error state is not displaying the error message correctly

### ISSUE THREAD

**Issue by jdirand** [codegouvfr/react-dsfr#62]
I am using the Select component in 2 projects and I have an issue with the error state : the error message is showing as a valid message (green with the check icon)

![image](https://user-images.githubusercontent.com/5951368/218797148-0a6cc16c-40e5-4e58-920c-9798c126fa32.png)

When I inspect the error message, the paragraph has 2 classes (fr-valid-text fr-error-text).

I am using the code from the story : https://react-dsfr-components.etalab.studio/iframe.html?viewMode=docs&id=components-select--error-state&args=#error-state

**Comment by enguerranws** [comment]
Can you provide the props you are giving to the `Select` component?

**Comment by jdirand** [comment]
I have copied the example from the storybook, the props are these one:
``` label="Label pour liste déroulante"
  nativeSelectProps={{}}
  state="error"
  stateRelatedMessage="Texte d’erreur obligatoire"
```

**Comment by garronej** [comment]
The storybook is the actual lib running, the code when you copy the code you're getting the actuall code that generates what you see in the storybook.  

The answer is to update `@codegouv/react-dsfr` to the latest version.  

Please let us know if your problem isn't solved.  

Best regads

**Comment by enguerranws** [comment]
Just tested it on a fresh Vite project, but I couldn't reproduce this behavior.

@jdirand I would also suggest to update to the latest version of `react-dsfr`.

**Comment by jdirand** [comment]
Thanks guys, working fine with the latest version!
