### ISSUE TITLE
Add partners to footer component

### ISSUE THREAD

**Issue by gary-van-woerkens** [codegouvfr/react-dsfr#78]
As described [here](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/pied-de-page), footer component might have a `partners` section.

**Comment by gary-van-woerkens** [comment]
Should be linked to #77 PR.

**Comment by gary-van-woerkens** [comment]
Following the implementation of the `partners` section in the footer component, I get a [live result](https://bpcomieux.fabrique.social.gouv.fr/) like this:
![image](https://user-images.githubusercontent.com/59922165/224379450-2f6d8065-4b6c-431e-85a1-c69ee2a4db22.png)

And I wonder... 🤔 

1. When there are 2 logos only, won't it be better to put them both together on the left or the right side?

And in this case I guess that `main` should become optional as well because only `sub` is supposed to be a list ?
https://github.com/codegouvfr/react-dsfr/blob/2c2022af96ee53560a78f71dc52eee2da3e6a3b2/src/Footer.tsx#L90-L93

2. The `target="_blank"` added to the links displays an icon next to the logos. Should we keep it like this?
![image](https://user-images.githubusercontent.com/59922165/224380632-b28fb62d-4976-41c9-91d3-c91a1e08f103.png)

**Comment by garronej** [comment]
You're probably not running the latest version.  
I patched your PR, check it out: https://github.com/codegouvfr/react-dsfr/pull/77#issuecomment-1463871817  

Hum yes, for the two logos you're probably right

**Comment by garronej** [comment]
For the case where ther's only two logo, I agree that it's a bit odd looking but react-dsfr has no say on this kind of things.  
It's an integration library that must align 100% with the vanilla implementation @gouvfr/dsfr.  
https://main--ds-gouv.netlify.app/example/component/footer/

**Comment by garronej** [comment]
What you can do is use the`classes.partnersLogos` props of the <Footer /> and make it look like just the way you want.

**Comment by gary-van-woerkens** [comment]
> It's an integration library that must align 100% with the vanilla implementation @gouvfr/dsfr.

About that I asked the DSFR team how the case with 2 partners icons only should be handled.

> Bonjour Gary,
>
> Vous pouvez voir les exemples ici https://main--ds-gouv.netlify.app/example/component/footer/
>
> Avec 2 logo partenaires, au choix, vous pouvez mettre un principal à gauche et un secondaire à droite ou bien les 2 en secondaire à droite.
>
> Bonne journée
>
> Bertrand pour l'équipe DSFR

My interpretation here is that `main` should become optional as `sub` is... but at least one of them must be declared.

**Comment by garronej** [comment]
> but at least one of them must be declared  

This is not easy to type, maybe it's best to have the first of the list being the main what do you think?

**Comment by gary-van-woerkens** [comment]
Here is my proposal to "solve" the issue: #81
