### ISSUE TITLE
Working on SideMenu component

### ISSUE THREAD

**Issue by gary-van-woerkens** [codegouvfr/react-dsfr#80]
Should be linked to PR #79.

#### Options
- [x] Multilevel menu
- [x] Max levels set to `3` (hardcoded)
- [x] Positioning (`sticky`, `sticky full height`, `aligned right`)
- [x] Responsive
- Examples :
    - [x] Next appdir
    - [x] Next pagesdir
    - [x] CRA
    - [ ] Vite

**Comment by gary-van-woerkens** [comment]
#### Question

There is a class to add to the selected menu item: `fr-sidemenu__item--active`.
I guess that the position of this class is related to something external to the SideMenu itself, as the app routing.

Any suggestion about the implementation of the item selection logic ?

**Comment by garronej** [comment]
Hello @gary-van-woerkens,  
Thank you for your effort,  
Please take a look at how the menu is already implemented, it should and must be consistent with how the side menu works.  

https://github.com/codegouvfr/react-dsfr/blob/main/src/MainNavigation/MainNavigation.tsx

**Comment by enguerranws** [comment]
I would say that it should be handled by a property, eg `active` prop, to keep dsfr naming which would be a boolean?

**Comment by garronej** [comment]
Yes, let's put `isActive` just to be consistent with whay we already do in the menu.  

The only place we don't use a `is|do|will|has` prefix is for level 0 component props because.  
`<Foo active />` make more sence than `<Foo isActive />`.  
Even if it's always possible to write `<Foo isActive={true} />`, it's less webby.

**Comment by gary-van-woerkens** [comment]
I get the following error:

```
src/SideMenu.tsx:60:85 - error TS2345: Argument of type '{ "fr-sidemenu__item--active": boolean; }' is not assignable to parameter of type 'FrCxArg'.
  Object literal may only specify known properties, and '"fr-sidemenu__item--active"' does not exist in type 'Partial<Record<FrClassName, boolean | null | undefined>> | readonly FrCxArg[]'.

60                                 <li key={i} className={fr.cx("fr-sidemenu__item", { "fr-sidemenu__item--active": isActive })}>
                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[6:00:42 PM] Found 1 error. Watching for file changes.
```

Should I add somehow `fr-sidemenu__item--active` to the list of allowed classes listed in `src/fr/generatedFromCss/classNames.ts`?

**Comment by garronej** [comment]
Everything in `generatedFromCss` is transpilled from the reference CSS stylesheet.  
The class `fr-sidemenu__item--active` not beeing present means that the official documentation is out of date and that it's something else that makes the item selected: `aria-current="page"` on the child.

**Comment by garronej** [comment]
https://filedn.com/lYPEPucNMheV19aDu23lK0Q/Etalab/Screen%20Recording%202023-03-15%20at%2018.27.26.mov

**Comment by gary-van-woerkens** [comment]
**SideMenu** component has been merged. Closing the issue.
Thank you for your help guys!
