### ISSUE TITLE
Working on Table component

### ISSUE THREAD

**Issue by gary-van-woerkens** [codegouvfr/react-dsfr#85]
Should be linked to PR #84.

#### Options

- [x] With borders
- [x] Without scroll
- [x] With fixed layout
- [x] With hidden caption
- [x] With bottom caption
- [x] With colour variants
- Examples :
	- [x] CRA
	- [x] Next appdir
	- [x] Next pagesdir
	- [x] Vite

**Comment by garronej** [comment]
Great thanks!
